### ISSUE TITLE
Windows IoT Core support

### ISSUE THREAD

**Issue by Valkyrie-MT** [respeaker/seeed-voicecard#10]
If y'all could cross compile to support Windows IoT Core, that would be great.  With Cortana already being built into Windows IoT Core, it would be great to have a mic like this!

**Comment by jerryyip** [comment]
Hi,
I am sorry that Win10 IoT Core does not support I2S as recording device. https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist
