### ISSUE TITLE
Error! There are no instances of module: seeed-voicecard 0.3 located in the DKMS tree.

### ISSUE THREAD

**Issue by martinweiss** [respeaker/seeed-voicecard#100]
I am having trouble setting up the ReSpeaker 2-mic array... I followed the instructions, but during the installation I get the following error messages:

```
Error! There are no instances of module: seeed-voicecard
0.3 located in the DKMS tree.

Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->
                 /usr/src/seeed-voicecard-0.3

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.14.69+ -C /lib/modules/4.14.69+/build M=/var/lib/dkms/seeed-voicecard/0.3/build........
cleaning build area.....

DKMS: build completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.14.69-v7+ -C /lib/modules/4.14.69-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build........
cleaning build area....

DKMS: build completed.
Error! echo
Your kernel headers for kernel 4.9.73+ cannot be found at
/lib/modules/4.9.73+/build or /lib/modules/4.9.73+/source.
Error! echo
Your kernel headers for kernel 4.9.73-v7+ cannot be found at
/lib/modules/4.9.73-v7+/build or /lib/modules/4.9.73-v7+/source.
git init
Initialized empty Git repository in /etc/voicecard/.git/
git add --all
git commit -m "origin configures"
[master (root-commit) 0f373e2] origin configures
 7 files changed, 1476 insertions(+)
 create mode 100644 ac108_6mic.state
 create mode 100644 ac108_asound.state
 create mode 100644 asound_2mic.conf
 create mode 100644 asound_4mic.conf
 create mode 100644 asound_6mic.conf
 create mode 100644 dkms.conf
 create mode 100644 wm8960_asound.state
Created symlink /etc/systemd/system/sysinit.target.wants/seeed-voicecard.service → /lib/systemd/system/seeed-voicecard.service.
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Enjoy!

```

The device doesn't show up when I do aplay -l and arecord -l. Does anyone know how to solve this? I'm running Raspbian Stretch Desktop on a Pi 2 B.

**Comment by Pillar1989** [comment]
The reason for this issue is that the ` apt-get-y install raspberrypi-rip-headers raspberrypi-kernel` failed during the installation process. You need to re-download the "raspberrypi-rip-headers raspberrypi-kernel", and then re-execute the ` install.sh ` for installation

**Comment by martinweiss** [comment]
Now I get

`E: Unable to locate package raspberrypi-rip-headers`

**Comment by Pillar1989** [comment]
Sorry,

`apt-get -y install raspberrypi-kernel-headers `

**Comment by martinweiss** [comment]
Thanks for the quick reply. When I do that I get

`raspberrypi-kernel-headers is already the newest version (1.20180910-1)`

**Comment by Pillar1989** [comment]
There are too many Linux kernels in your system, such as 4.14.69+, 4.14.69-v7+,  4.9.73+, 4.9.73-v7+.From the installation information, currently seeed-voicecard can only work under 4.14.69+ and 4.14.69-v7+.If you reboot the system, the kernel is one of the two versions, and your seeed-voicecard can be working.

**Comment by martinweiss** [comment]
Can you please tell me how I remove the old kernels? When I do uname -a I get

`Linux raspberrypi 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux`

**Comment by martinweiss** [comment]
This is the output of the commands: 

```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
```

So it seems like something is wrong...

**Comment by Pillar1989** [comment]
`cat /var/log/seeed-voicecard.log`  What the log show。

**Comment by martinweiss** [comment]
Output:

```
pi@raspberrypi:~ $ cat /var/log/seeed-voicecard.log 
+ dtparam i2c_arm=on
+ modprobe i2c-dev
+ dtparam spi=on
+ sleep 1
++ i2cdetect -y 1 0x1a 0x1a
++ grep 1a
++ awk '{print $2}'
+ is_1a=1a
++ i2cdetect -y 1 0x35 0x35
++ grep 35
++ awk '{print $2}'
+ is_35=
++ i2cdetect -y 1 0x3b 0x3b
++ grep 3b
++ awk '{print $2}'
+ is_3b=
+ rm /etc/asound.conf
+ rm /var/lib/alsa/asound.state
+ '[' x1a == x1a ']'
+ '[' x == x ']'
+ echo 'install 2mic'
install 2mic
+ dtoverlay seeed-2mic-voicecard
+ sleep 1
+ echo 'create 2mic asound configure file'
create 2mic asound configure file
+ ln -s /etc/voicecard/asound_2mic.conf /etc/asound.conf
+ echo 'create 2mic asound status file'
create 2mic asound status file
+ ln -s /etc/voicecard/wm8960_asound.state /var/lib/alsa/asound.state
+ '[' x == x3b ']'
+ '[' x == x3b ']'
+ alsactl restore
+ amixer cset numid=3 1
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=1
```

**Comment by Pillar1989** [comment]
```
sudo rm /lib/modules/4.9.73+
sudo rm /lib/modules/4.9.73-v7+
sudo  ./uninstall.sh 
```
I think you need to delete the old kernel module and reinstall it.

**Comment by martinweiss** [comment]
Thanks I'll try that. When I ran uninstall.sh I got the following output:

```
pi@raspberrypi:~/seeed-voicecard $ sudo ./uninstall.sh 
remove dtbos
remove alsa configs
disabled seeed-voicecard.service 
Removed /etc/systemd/system/sysinit.target.wants/seeed-voicecard.service.
remove seeed-voicecard
remove dkms
remove kernel modules
rm: cannot remove '/lib/modules/4.14.69-v7+/kernel/sound/soc/codecs/snd-soc-wm8960.ko': No such file or directory
rm: cannot remove '/lib/modules/4.14.69-v7+/kernel/sound/soc/codecs/snd-soc-ac108.ko': No such file or directory
rm: cannot remove '/lib/modules/4.14.69-v7+/kernel/sound/soc/bcm/snd-soc-seeed-voicecard.ko': No such file or directory
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Thank you!
------------------------------------------------------
```

Isn't that a bit strange?

**Comment by Pillar1989** [comment]
This is because it was installed incorrectly the previous time. Just ignore it.

**Comment by martinweiss** [comment]
Great, it works now! Thanks a lot for your help. Maybe it's worth adding this information somewhere.

```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Also, I think I learnt a lot the past few hours. Thanks again for helping.

**Comment by Kuldeepwadaskar** [comment]
> Great, it works now! Thanks a lot for your help. Maybe it's worth adding this information somewhere.
> 
> ```
> pi@raspberrypi:~ $ aplay -l
> **** List of PLAYBACK Hardware Devices ****
> card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
>   Subdevices: 7/7
>   Subdevice #0: subdevice #0
>   Subdevice #1: subdevice #1
>   Subdevice #2: subdevice #2
>   Subdevice #3: subdevice #3
>   Subdevice #4: subdevice #4
>   Subdevice #5: subdevice #5
>   Subdevice #6: subdevice #6
> card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> pi@raspberrypi:~ $ arecord -l
> **** List of CAPTURE Hardware Devices ****
> card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> ```
> 
> Also, I think I learnt a lot the past few hours. Thanks again for helping.

i am facing same error, can you please explain me step by step how to do perfect installation so that arecord -l will show devices?
uname -r 
4.19.50-v7+

**Comment by Kuldeepwadaskar** [comment]
> There are too many Linux kernels in your system, such as 4.14.69+, 4.14.69-v7+, 4.9.73+, 4.9.73-v7+.From the installation information, currently seeed-voicecard can only work under 4.14.69+ and 4.14.69-v7+.If you reboot the system, the kernel is one of the two versions, and your seeed-voicecard can be working.
-------------------------------------------------------------------------------------------------------------------
.................
..................
...................
Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->
                 /usr/src/seeed-voicecard-0.3

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make KERNELRELEASE=4.19.50+ -C /lib/modules/4.19.50+/build M=/var/lib/dkms/seeed-voicecard/0.3/build......(bad exit status: 2)
ERROR (dkms apport): binary package for seeed-voicecard: 0.3 not found
Error! Bad return status for module build on kernel: 4.19.50+ (armv7l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make KERNELRELEASE=4.19.50-v7+ -C /lib/modules/4.19.50-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build......(bad exit status: 2)
ERROR (dkms apport): binary package for seeed-voicecard: 0.3 not found
Error! Bad return status for module build on kernel: 4.19.50-v7+ (armv7l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make KERNELRELEASE=4.19.50-v7l+ -C /lib/modules/4.19.50-v7l+/build M=/var/lib/dkms/seeed-voicecard/0.3/build......(bad exit status: 2)
ERROR (dkms apport): binary package for seeed-voicecard: 0.3 not found
Error! Bad return status for module build on kernel: 4.19.50-v7l+ (armv7l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.
.......................
.........................
.....................
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Enjoy!
------------------------------------------------------

i am getting this error, not able to make files. 
problem with binary.
can you please help me to understand this problem and solve it?

**Comment by MustafaAnasKH99** [comment]
This solution did not work for me nowadays coz installing the seeed-voicecard automatically updates the kernel to 4.19.
Any idea how to solve this??? I have been trying to get my 2-mic hat to work with my pi w zero for few days by now. It is frustrating
