### ISSUE TITLE
[Respeaker4] - Statics, very bad statics

### ISSUE THREAD

**Issue by Psychokiller1888** [respeaker/seeed-voicecard#102]
Using a respeaker 4 on a raspberry pi 3b+, recording using your wiki test settings. Changed rate to 42k to see if any difference, it's the same, the statics just being higher tuned

How do I fix this?

[respeaker4.zip](https://github.com/respeaker/seeed-voicecard/files/2430545/respeaker4.zip)

**Comment by Psychokiller1888** [comment]
And yes, alsamixer is set up

![https://i.imgur.com/Ysvjni1.png](https://i.imgur.com/Ysvjni1.png)

**Comment by Psychokiller1888** [comment]
This is PGA set to 0....

[test.zip](https://github.com/respeaker/seeed-voicecard/files/2442961/test.zip)

So it doesn't work

**Comment by Psychokiller1888** [comment]
And this is the result of these settings:

![https://i.imgur.com/pUWehJs.png](https://i.imgur.com/pUWehJs.png)

You don't even hear me speaking....

[test.zip](https://github.com/respeaker/seeed-voicecard/files/2442973/test.zip)

**Comment by xiongyihui** [comment]
How did you record?

Try `arecord -f S16_LE -r 48000 -c 4 -v audio.wav` to record 4 channels audio, and use audacity to check each channel to verify if any microphone is broken.

To check if the ADC is broken or not, we can use a tape to seal the microphone's hole, and check if there are any difference.

**Comment by Psychokiller1888** [comment]
Using your settings

[audio.zip](https://github.com/respeaker/seeed-voicecard/files/2457268/audio.zip)

**Comment by Psychokiller1888** [comment]
![https://i.imgur.com/BtvMkPW.png](https://i.imgur.com/BtvMkPW.png)

**Comment by xyu6** [comment]
Hi there, 

please try to reduce the capture vol to 50% and see if any issue. If the issue is still there, please drop a mail to techsupport@seeed.cc. thanks. 

best rgds
Bill

**Comment by Psychokiller1888** [comment]
Same, but at least I did not bleed from my ears when aplaying this time, as it's lower....

[audio.zip](https://github.com/respeaker/seeed-voicecard/files/2463957/audio.zip)

![Imgur](https://i.imgur.com/5laWIEv.png)

![Imgur](https://i.imgur.com/bTfDW3V.png)

**Comment by Pillar1989** [comment]
It looks like there's something wrong with your hardware. It can't be the sound of our microphone array.

**Comment by Psychokiller1888** [comment]
Yes, it looks, or sounds like there's something wrong, but what?

**Comment by Psychokiller1888** [comment]
So what, I wrote an email with no answers and as a solution you saying it's not your microphone???

**Comment by xiongyihui** [comment]
@xyu6

**Comment by Psychokiller1888** [comment]
The support for your product is really really hopeless

**Comment by xyu6** [comment]
Hi there, what about your email address? I will follow up with you directly and then work on the return process. Sorry, we do not receive your mail on techsupport@seeed.cc mail system. It may be the mail delivery issue. thanks for understanding. Or you can drop bill.yu@seeed.cc directly. thanks.

**Comment by daenuprobst** [comment]
I have similar problems, there is quite some static when recording (that or the recording volume is really low). Did you manage to fix the problem @Psychokiller1888

**Comment by Psychokiller1888** [comment]
Throw your respeaker to trash and get something else. There's nothing to be done and seeed will not help you in fixing the issue

**Comment by ejay-ibm** [comment]
Got the same issue . I have better sound with a 5 euro simple USB mic . 
I try all tunning setting i'm still getting trashy noise that prevent clear speech . 
Sad.
