### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by pvklink** [respeaker/seeed-voicecard#104]
i did a fresh install of my rpi 3b with seeed respeaker 2-mics and used this manual

https://www.pcactive.nl/workshops/1664-je-eigen-google-home-assistent

Everything works, except the audio! 
I did this install two monts ago and then everything did work!

source env/bin/activate
 env/bin/google-assistant-demo
[FATAL:audio_input_stream.cc(47)] Input device could not be opened: default
Afgebroken

arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by Pillar1989** [comment]
This is the problem with the google-assistant-demo.Ask for help with google-assistant.
