### ISSUE TITLE
Audio not working for Respeaker 6-mic on Raspberry Pi 3

### ISSUE THREAD

**Issue by bpmct** [respeaker/seeed-voicecard#105]
Opening up a new issue because I took too long to respond on issue [101](https://github.com/respeaker/seeed-voicecard/issues/101), and it was closed.

I'm unable to get microphone audio working, however I can get the LEDs to display just fine.

I installed a fresh OS and tried with the drivers and same exact result.

I even tried using the image with the drivers pre-installed. Same exact results, even from the CLI. I also tried re-seating the cable multiple times.

Attached is the 10s file that I recorded via the command line. It has no sound at all. What else can I do?

[d.wav.tar.gz](https://github.com/respeaker/seeed-voicecard/files/2475930/d.wav.tar.gz)

_Originally posted by @bpmct in https://github.com/respeaker/seeed-voicecard/issues/101#issuecomment-429582672_

**Comment by Pillar1989** [comment]
Hi, Can you show me your alsamixer configure ?

**Comment by bpmct** [comment]
Hi @Pillar1989. Thanks for the response:

Attached was my current alsamixer config:

![screenshot at 2018-10-15 08-26-08](https://user-images.githubusercontent.com/22407953/46960937-814df400-d054-11e8-9d3c-71afb723b518.png)
![screenshot at 2018-10-15 08-25-55](https://user-images.githubusercontent.com/22407953/46960938-81e68a80-d054-11e8-9617-b54efdc9cb35.png)
![screenshot at 2018-10-15 08-25-26](https://user-images.githubusercontent.com/22407953/46960939-81e68a80-d054-11e8-9bfa-bf98289dcb2d.png)
![screenshot at 2018-10-15 08-25-01](https://user-images.githubusercontent.com/22407953/46960940-81e68a80-d054-11e8-94b9-dd41c5e1d949.png)

I also tried with all values at 90% and I am still having no luck recording with audio.

**Comment by Pillar1989** [comment]
in https://github.com/respeaker/seeed-voicecard/issues/101#issuecomment-429582672_  There was a voice in your previous comments, but the voice was not correct. Now there is no voice at all. Can you describe your problem clearly if you want our help?

![screenshot at 2018-10-15 08-26-08](https://user-images.githubusercontent.com/22407953/45605317-111a6700-b9f1-11e8-89b5-3a1d3d99f7ec.png)

**Comment by bpmct** [comment]
@Pillar1989 My issue is that my microphone is not recording any audio. It just returns an empty audio file. What do you mean there was a voice in my previous comments?

**Comment by Pillar1989** [comment]
Yes

**Comment by bpmct** [comment]
@Pillar1989 I don't understand sorry. Could you please explain?

**Comment by Pillar1989** [comment]
@bpmct Will close this issue, please open a new issue if you have further questions.
