### ISSUE TITLE
Seeed-voicecard transplant to Android based raspberry pie problem

### ISSUE THREAD

**Issue by xshodow** [respeaker/seeed-voicecard#109]
Seeed-voicecard in the Linux environment, I can achieve the recording function. If I'm going to transplant the seed-voicecard-4mic driver to a raspberry pie running Android, what do I do?
I am configured in the /boot/config.txt file as follows:
Hdmi_group=2
Hdmi_drive=2
Hdmi_mode=87
Hdmi_cvt=1280 720606000
Hdmi_force_hotplug=1
Disable_overscan=1

Dtoverlay=vc4-kms-v3d, cma-256
Avoid_warnings=2

Dtparam=sd_force_pio=on
Dtparam=i2c1=on
Dtparam=i2c_arm=on
Dtoverlay=i2s-mmap
Dtparam=i2s=on

#dtparam=audio=on
Dtoverlay=seeed-4mic-voicecard
Audio_pwm_mode=2

Initial_turbo=30
Start_x=1
Kernel=u-boot.bin

Using the ADB debugging tool, it is found that there are only two sound cards currently loaded, and there is no seeed-voicecard device:
C:\Users\Administrator\Desktop>adb shell dmesg
[1.761369] ALSA device list:
[1.761438] #0: vc4-hdmi
[1.761493] #1: bcm2835 ALSA

I have no idea now. I hope you can put forward some ideas.

**Comment by Pillar1989** [comment]
Raspberrypi doesn't have an official Android system yet
