### ISSUE TITLE
how to mute mic array

### ISSUE THREAD

**Issue by Devanshi1510** [respeaker/seeed-voicecard#115]
Hi, I want to mute mic array. I tried this command from pulseaudio:  pactl set-source-mute 1 toggle 
But It didnt disable mic array when I tried to record voice using pactl set-source-mute 1 toggle I was able to record my voice,
While volume control was possible using pactl. I want to mute and unmute mic array like alexa/google home provides.

**Comment by baorepo** [comment]
Can you tell me which mic array is used ?

**Comment by Devanshi15** [comment]
ReSpeaker mic array V2.0 @baorepo

**Comment by Pillar1989** [comment]
I'm so sorry, I didn't find the option which you want in usb_4_mic_array software.
https://github.com/respeaker/usb_4_mic_array/blob/master/tuning.py#L19

But I think "mute mic array" is easy to implement in your application. "mute mic array" means get zero from the sound card. Replace real data with zero

**Comment by Devanshi15** [comment]
I implemented it using pulseaudio and it works using this command  - pacmd set-source-mute <index> 1 
Thank you for help!!!

**Comment by Pillar1989** [comment]
I will close this issue, the later you still have questions, you can reopen it
