### ISSUE TITLE
ALSA overrun occurred while using Respeaker 4 Mic Array

### ISSUE THREAD

**Issue by LordTyrion123** [respeaker/seeed-voicecard#118]
I've been using the Respeaker 4 mic Array with a Raspberry Pi 3. As of late, I've been getting the following error.
`ALSA lib pcm.c:8306:(snd_pcm_recover) overrun occurred`

I realize it is due to an improper `.asoundrc` file. I've tried setting the `buffer_size = 32678` but to no avail. The error just comes later. Is there a proper buffer_size I should use for the 4 Mic Array?

**Comment by baorepo** [comment]
you can describe this  problem detail? How do I reproduce this bug do?

**Comment by LordTyrion123** [comment]
It all started when I added a .asoundrc file and /etc/asound.conf to enable Snowboy with Google Assistant. Ever since then, I've been getting the above error.  It doesn't affect the code per se, but since the buffer is overruning, I assume that some recognized sound is being lost. I tried adding a buffer_size, but it only delayed the error from coming. I'll attach the .asoundrc and /etc/asound.conf files below.

asoundrc

`
pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        buffer_size 35840
        channels 4
    }
}
pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "hw:0,1"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}
`

/etc/asound.conf

`
pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:seeed4micvoicec"
        buffer_size 35840
        channels 4
    }
}
pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "hw:ALSA"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}
`

**Comment by turmary** [comment]
hi @LordTyrion123 ,
Your settings of /etc/asound.conf and asoundrc has no issue I think.
1. Below capturing command will no overrun : 
  **arecord -f S32_LE -r 48000 -c 4 /run/to_be_record.wav -v** 
2. Below capturing command will have much overruns:
  **arecord -f S32_LE -r 48000 -c 4 /home/pi/to_be_record.wav -v** 

Above arecord example 1 shows the capturing stuck at SD Card file storage (/home/pi/ mount to SD Card).
But arecord example 2 which record to RAM(tmpfs on /run type tmpfs) works file.

To prevent the occruing of overrun condition , the alsa audio application require a enough quick speed of reading record data.
If you use SD Card to store recording data, please use  a high speed class (Above or equal Class #10)  one.

**Comment by turmary** [comment]
Will close this issue, please open a new issue if you have further questions.
