### ISSUE TITLE
Compatibility with Intel based UP Board

### ISSUE THREAD

**Issue by plkumar** [respeaker/seeed-voicecard#120]
Hi,

Is the 6mic array compatible with AEON UP Board, which claims to have RaspberryPi compatible 40pin header, can these drivers be compiled for Intel Architecture?

https://up-board.org/up/specifications/

Thanks
Lakshman

**Comment by turmary** [comment]
Hi, 
It can't work on Intel Architecture even if it's compiling passed I think.
Most time sound card associate with CPU DAI & Codec DAI.
You can try to port it to Intel Architecture, but 2mic's porting will be easy than 6mic I think, 
caused by the strong optimizing for 6mic working with RPi.
