### ISSUE TITLE
How to modify i2c bus name

### ISSUE THREAD

**Issue by AndreV2890** [respeaker/seeed-voicecard#122]
Hi,

I have successfully installed the driver on a Raspberry Stretch. 
In my project, I have to work with the ReSpeaker 2-Mics Pi HAT, anyway, I have to overlay the default GPIO configuration. 
From some first trials, it seems that the driver works only if the i2c-1 (GPIO3 and GPIO5) is used. When I try to overlay from the "/boot/config.txt" file the default i2c configuration to use the GPIO23 and 24 a new i2c bus is created (called i2c-3).

Questions:
1. Is it correct that the driver searches for devices attached to the i2c-1 bus?
2. Is there any possibility to modify the number of the i2c bus?

**Comment by Pillar1989** [comment]
This is fixed on hardware and cannot be modified.

**Comment by AndreV2890** [comment]
Thanks @Pillar1989 for your immediate response.

Only just some few words to better clarify the problem. Maybe I explain it too quickly. 
In my system, I have a Resp connected to a Raspberry Pi running Stretch. On the Raspberry side, I have installed the driver. Once the Resp is attached I can test how it works running the ALSA form the command line or the equivalent in c code. In any case, the Raspberry and the Resp communicate using i2c-1 (the default one). 
With the aim to use the Res in a more complex system I have to modify the communication link between the Raspberry and the Resp because the i2c-1 is already used from another device. So the first problem is related to this topic. In particular, in a scenario where I connect the Raspberry and the Resp with some jumper cables, can I connect the GPIO 3,5 (on Resp) to another GPIO pins on Raspberry (maybe GPIO 23,24)? If it is feasible, have I to modify something in the driver?

**Comment by Pillar1989** [comment]
I2c is software compatible according to different device addresses, no need to modify the pin.

**Comment by Pillar1989** [comment]
I will close this issue, the later you still have questions, you can reopen it
