### ISSUE TITLE
ReSpeaker 4 Mic Array have a 30° error

### ISSUE THREAD

**Issue by linan2** [respeaker/seeed-voicecard#126]
When I use for respeaker to do doa I found that some angle is not accurate. For example, the neighbouring angle should have a 90° different but maybe my board have a 120° or 60° angle different. I will get the same situation when use for the original code and my own DOA code.

**Comment by jerryyip** [comment]
@linan2 have you checked the phase and frequency response of your recordings? How are they?

**Comment by Pillar1989** [comment]
I will close this issue, the later you still have questions, you can reopen it
