### ISSUE TITLE
Question - How to use button on ReSpeaker 6-mic Circular Array?

### ISSUE THREAD

**Issue by goliath789** [respeaker/seeed-voicecard#138]
I am using ReSpeaker 6-Mic Circular Array.
there seems a tact switch on array, but I couldn't find any information about it.

Which pin is connected to this button?
Is the button pulled up to 3V3?
If is the button is pulled up, how much resistor value?

**Comment by turmary** [comment]
Hi,
The button connected to RPi Expand SLOT pin 37(RPi GPIO26), with a 10K pullup resister to 3V3.

**Comment by goliath789** [comment]
Thank you for quick response!
