### ISSUE TITLE
pyaudio record and play simultaneously with the seeed-soundcard not correct

### ISSUE THREAD

**Issue by PhanLeSon03** [respeaker/seeed-voicecard#144]
Hello,
I am using Respeaker Circular Array board and try to to record and play simultaneously but the playout path is not running correctly: sometime it generates the sound and sometime it silences. 
The same python code could run correctly with soundcard on RPI for playing and seeed-soundcard for recording. I expect to play and record simulateously on the seeed-soundcard, can you give some hints?

**Comment by baorepo** [comment]
This issue I think this document should be helpful to you. https://people.csail.mit.edu/hubert/pyaudio/docs/ 
Or better yet, put your question under the topic https://stackoverflow.com/questions/tagged/pyaudio
