### ISSUE TITLE
Respeaker 4 mics array and Linux USB Audio Gadget

### ISSUE THREAD

**Issue by letourng** [respeaker/seeed-voicecard#154]
Hello, 

I'm trying to use respeaker mic array v1 with raspberry pi zero in USB mode. I would like to capture audio samples with the respeaker in 4 channels at 44100khz and send audio samples through USB. To do the job, I used USB audio gadget driver in the kernel on raspberry pi zero.

I used the following command:

arecord -Dsysdefault:CARD=seeed4micvoicec -c 4 -r 44100 -t raw -f S32_LE | aplay sysdefault:CARD=UAC1Gadget -f S32_LE -c 4 -r 44100
 
Results: Overrun with alsa

I also used the alsaloop command in root to have more priority on the thread but there're still to have overruns.

alsaloop -C sysdefault:CARD=seeed4micvoicec -P sysdefault:CARD=UAC1Gadget -f S32_LE -c 4 -c 44100 -A 3 -S 1 -b -v

So some audio packet are missed in the audio file receive to usb.

Do you have some ideas to improve that?

Best regards

**Comment by Pillar1989** [comment]
First of all, we must ensure that UAC1Gadget is stable. It has been tried by other users before, and it is very unstable.

**Comment by letourng** [comment]
Ok so there are non solutions to use respeaker in USB mode?

Le lun. 29 avr. 2019 à 03:14, Baozhu Zuo <notifications@github.com> a
écrit :

**Comment by baorepo** [comment]
To solve the stability problem of UAC1Gadget first, the main technical difficulty lies not in the seeed-voicecard side.

**Comment by letourng** [comment]
Ok,

you said your team has been worked on UAC1gadget. What is the main issue in linux UACGadget side? 
Do you have any idea ?

**Comment by Pillar1989** [comment]
We didn't analyze it in depth. We just did the test. The function we wanted was replaced by https://www.seeedstudio.com/ReSpeaker-Mic-Array-v2-0.html .

**Comment by letourng** [comment]
Ok, 

Respeaker v2 supported 44Khz and 48khz 4 channels ?

**Comment by jerryyip** [comment]
@letourng ReSpeaker Mic Array v2 supports only 48KHz and 16KHz by [different firmwares](https://github.com/respeaker/usb_4_mic_array), and it can output 6 channels(1 processed audio, 4 raw microphone audio, 1 reference channel audio).
