### ISSUE TITLE
How to use echo cancellation in 2-Mic Hat?

### ISSUE THREAD

**Issue by sosorry** [respeaker/seeed-voicecard#155]
I follow the instruction.
[https://github.com/voice-engine/ec](https://github.com/voice-engine/ec)

I can record and playback with these commands.
```
./ec -i plughw:1 -o plughw:1 -s
cat /tmp/ec.output > 16k_s16le_stereo_audio.raw
cat 16k_s16le_stereo_audio.raw > /tmp/ec.input
```

How can I enable echo cancellation directly without `cat` command?

I tried to install FIFO plugin and copy [asound.conf](https://github.com/voice-engine/ec/blob/master/asound.conf) to ~/.asoundrc but no luck.

While I record the audio using `arecord -d 3 -f dat test.wav`, the error message is
```
ALSA lib pcm.c:7448:(snd_pcm_slave_conf) Unknown field type
arecord: main:788: audio open error: Invalid argument
```

My environment is `uname -a`:
```
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
```
Thanks

**Comment by Pillar1989** [comment]
@sosorry This is a basic programming skill. We don't have much time to help you with these details
