### ISSUE TITLE
No sound on raspbian 2018-11-13

### ISSUE THREAD

**Issue by tangb** [respeaker/seeed-voicecard#157]
Hello

I installed my respeaker2mic in "old" raspbian installation (2018-11-13). Install run fine, no error. I can see the seeed soundcard in aplay -l. Also I can play with leds without problem.

My problem is when I play file there is no sound from audio jack. Also when I'm trying to record audio, command run well but nothing is recorded (I played recorded wave file on other computer).

I tested the respeaker2mic hat on fresh raspbian install (2019-04-08) and I got no problem, audio files played fine on it. Recordings worked well too.

I would like to understand what's happening on my "old" install and try to fix it because reinstalling all my stuff will give me a lot of pain :-(. And my curiosity wants to understand the problem ;-)

Can you help me investigating ? (I spent all my afternoon yet and no clue)

Here is some commands outputs:
dmesg: https://gist.github.com/tangb/032da6008a3885ccb3253656677ec943
lsmod: https://gist.github.com/tangb/3ce0daf587d4615287948377d3a2cdb0
aplay -l + arecord -l: https://gist.github.com/tangb/e21ae82bde6e17e417d2ee42f49e76c0
aplay sample: https://gist.github.com/tangb/7c9b499c3ee11ce4b951b938b7f8855a
test record+play: https://gist.github.com/tangb/ebeaeb99c3e3718f6cd35f53da5a7780

Thank you very much ;-)

**Comment by Pillar1989** [comment]
On the mirror of 2018-11-13, we did not encounter any problem from the ohter user. I hope you can check the ALSA Settings in the system. It's probably something you set up yourself.
