### ISSUE TITLE
Respeaker 2 Mic on PI Zero (strech) not found

### ISSUE THREAD

**Issue by opl-git** [respeaker/seeed-voicecard#160]
Hello,
I am using a raspberry pi zero 1.1 W running the lastet debian strech release (2019-04-08).
Before the installation I did the usual install stuff (apt-get update/upgrade, expand filesystem, change localization to germany).
I tried to install the Respeaker 2 Mics Version like described here:
`git clone https://github.com/respeaker/seeed-voicecard
cd seeed-voicecard
sudo ./install.sh 
sudo reboot`

It looks like everything went well, but after the reboot I can`t find the respeakercard with _aplay -l_ or _arecord - l_

Is there something I forgot?
Hope someone may help me :)

**Comment by Pillar1989** [comment]
Duplicate of #160

**Comment by Pillar1989** [comment]
#160

**Comment by opl-git** [comment]
I am confused... this is a duplicate of my own question?
You closed it, because it is a duplicate of #160 which is my issue...

**Comment by Pillar1989** [comment]
I am really sorry, your question should be duplicated with 159. I filled in the wrong number.

**Comment by opl-git** [comment]
I see. 😊
So it is because of the new kernel.
I am looking forward for your patch, thank you very much for your efforts.
