### ISSUE TITLE
Unable to install seed voice card on Ubuntu mate 18.04.2 LTS

### ISSUE THREAD

**Issue by kavi1929** [respeaker/seeed-voicecard#165]
I using ubuntu mate on my raspberry PI 3. On this stretch am unable to install seed-voicecard, as I get following errors.

> boot/overlays not found or not a directory
dtparam not found
dtoverlay not found

Following is my system version. Someone please help me.

>uname -a  
Linux rtips-desktop 4.15.0-1032-raspi2 #34-Ubuntu SMP PREEMPT Wed Feb 6 11:46:23 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

> cat /boot/issue.txt
cat: /boot/issue.txt: No such file or directory

**Comment by Pillar1989** [comment]
Sorry, We only support official operating system for all models of the Raspberry Pi.
