### ISSUE TITLE
Reset occurs when activating Respeaker 4 LEDs on RPi zero 

### ISSUE THREAD

**Issue by onurtam35** [respeaker/seeed-voicecard#169]
when working with Respeaker 4, RPi zero restarts after driving GPIO5 high level as below.

pi@raspberrypi:~ $ echo "5">/sys/class/gpio/export
pi@raspberrypi:~ $ echo "out">/sys/class/gpio/gpio5/direction
pi@raspberrypi:~ $ echo "1">/sys/class/gpio/gpio5/value
Connection reset by 169.254.245.116 port 22

any solution?

**Comment by Pillar1989** [comment]
Our test did not find the problem you mentioned
