### ISSUE TITLE
Unable to get Status Code 204 

### ISSUE THREAD

**Issue by tarunl** [respeaker/seeed-voicecard#17]
I followed the sets of commands given in following article
http://wiki.seeed.cc/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/

But after being done with the commands. No Status code 204 is received after running
"python ns_kws_doa_alexa_with_light.py"

Please help me to find the issue.

Following is the log file.........

ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_ac108.c:469:(_snd_pcm_ac108_open) a108 is only for capture
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:0:bcm2835 ALSA: - (hw:0,0) with 0 input channels
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:1:bcm2835 ALSA: IEC958/HDMI (hw:0,1) with 0 input channels
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:2:seeed-4mic-voicecard: - (hw:1,0) with 2 input channels
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:3:sysdefault with 0 input channels
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:4:playback with 0 input channels
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:5:dmixed with 0 input channels
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:6:ac108 with 4 input channels
INFO:/home/pi/env/local/lib/python2.7/site-packages/voice_engine-0.0.3-py2.7.egg/voice_engine/source.pyc:Use ac108
INFO:avs.alexa:Refreshing access_token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.amazon.com
DEBUG:urllib3.connectionpool:https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 977
DEBUG:avs.alexa:{
"product_id": "ReSpeaker",
"access_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"refresh_url": "https://api.amazon.com/auth/o2/token",
"expiry": "Thu Dec 07 12:49:45 2017",
"api": "v20160207",
"client_id": "amzn1.application-oa2-client.xxxxxxxxxxxxxxxxxxxxxxxxxx",
"host_url": "avs-alexa-na.amazon.com",
"client_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"refresh_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
DEBUG:hyper.http20.connection:Selected NPN protocol: h2
DEBUG:hyper.http20.connection:recv for stream 0 with set([]) already present
INFO:hyper.http20.connection:Received unhandled event <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=100), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=2147483647), ChangedSetting(setting=SettingCodes._max_header_list_size, original_value=None, new_value=40960)}>
INFO:hyper.http20.connection:Received unhandled event <WindowUpdated stream_id:0, delta:2147418112>
DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0x73e4ac88>
DEBUG:hpack.hpack:Adding (':method', 'GET') to the header table
ALSA lib pcm.c:8306:(snd_pcm_recover) overrun occurred
DEBUG:hpack.hpack:Encoding 2 with 7 bits
DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hpack.hpack:Encoding 7 with 7 bits
DEBUG:hpack.hpack:Adding (':authority', 'avs-alexa-na.amazon.com') to the header table
DEBUG:hpack.hpack:Encoding 1 with 6 bits
DEBUG:hpack.hpack:Encoding 17 with 7 bits
DEBUG:hpack.hpack:Adding (':path', '/v20160207/directives') to the header table
DEBUG:hpack.hpack:Encoding 4 with 6 bits
DEBUG:hpack.hpack:Encoding 15 with 7 bits
DEBUG:hpack.hpack:Adding ('authorization', 'Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx') to the header table
DEBUG:hpack.hpack:Encoding 23 with 4 bits
DEBUG:hpack.hpack:Encoding 474 with 7 bits
DEBUG:hpack.hpack:Encoded header block to ��A��t,:
�kT5�H����z�D��� :Ć��I�������Q�[��>��2x�w&Z��RpŲ�d����gl2{�����(���{6���Vtلz����U������ii̋%�I�ʍ���q��{/���إg6�l����~���1�k�����������͎Д�?W������&�ut{�5�
�O��n��o�f�sg)|���g纟ވl�;4���tMژ�F�y��E�s�ڰ����˶O�:ͨ�|���^�mr^"�
Y����lכVP6���ǫ$��-��p�O#~�߽�������[����zeoe����������ѥ�)ܣ�����+����W�o��ڒ���vJ{���}E�??�1X�+vF�<�,�ͺb� �;gf��ӣV����;�;����g��çk �)EӮH�����O>|;��T��E�0mK;,)�{A�U���߿Q�FyÛoK�۵���;��e����P�WNhݮ�f DEBUG:hyper.http20.connection:recv for stream 1 with set([]) already present INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{ChangedSetting(setting=SettingCodes.ENABLE_PUSH, original_value=1, new_value=0)}> INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{}> DEBUG:hyper.http20.connection:recv for stream 1 with set([]) already present DEBUG:hpack.hpack:Decoding �T�*@�����R����BM'���tOK,�fBH�K�DrE�����.1���"��k9#/F%��H�mR�P,��,��$��Q>�,��� A�ǩ=_ DEBUG:hpack.hpack:Decoded 8, consumed 1 bytes DEBUG:hpack.hpack:Decoded (':status', '200'), consumed 1 DEBUG:hpack.hpack:Decoded 20, consumed 1 bytes DEBUG:hpack.hpack:Decoded 1, consumed 1 bytes DEBUG:hpack.hpack:Decoded ('access-control-allow-origin', <memory at 0x73eb4f80>), total consumed 3 bytes, indexed True DEBUG:hpack.hpack:Decoded 12, consumed 1 bytes DEBUG:hpack.hpack:Decoded 44, consumed 1 bytes DEBUG:hpack.hpack:Decoded ('x-amzn-requestid', '06c728fffe3dcd94-00004c6d-0000c350-3d16aba23a82e67b-6d39ad0b-1'), total consumed 59 bytes, indexed True DEBUG:hpack.hpack:Decoded 31, consumed 1 bytes DEBUG:hpack.hpack:Decoded 47, consumed 1 bytes DEBUG:hpack.hpack:Decoded ('content-type', 'multipart/related; boundary=------abcde123; type=application/json'), total consumed 49 bytes, indexed True INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:1, weight:16, depends_on:0, exclusive:False> DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0x73e5c210> DEBUG:hpack.hpack:Adding (':method', 'POST') to the header table DEBUG:hpack.hpack:Encoding 3 with 7 bits DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table DEBUG:hpack.hpack:Encoding 7 with 7 bits DEBUG:hpack.hpack:Adding (':authority', 'avs-alexa-na.amazon.com') to the header table DEBUG:hpack.hpack:Encoding 63 with 7 bits DEBUG:hpack.hpack:Adding (':path', '/v20160207/events') to the header table DEBUG:hpack.hpack:Encoding 4 with 6 bits DEBUG:hpack.hpack:Encoding 12 with 7 bits DEBUG:hpack.hpack:Adding ('content-type', 'multipart/form-data; boundary=seeed-voice-engine') to the header table DEBUG:hpack.hpack:Encoding 31 with 6 bits DEBUG:hpack.hpack:Encoding 34 with 7 bits DEBUG:hpack.hpack:Adding ('authorization', 'Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx') to the header table DEBUG:hpack.hpack:Encoding 23 with 4 bits DEBUG:hpack.hpack:Encoding 474 with 7 bits DEBUG:hpack.hpack:Encoded header block to ���D�c��� :�{���_����j�bX��R��H�Ԍ�� ��� Rȷs��X�Lj�����Q�[��>��2x�w&Z��RpŲ~�d����gl2{�����(���{6�~��Vtلz����U������ii̋%�I�ʍ���q��{/���إg6�l����~���1�k�����������͎Д�?W������&�ut{�5� �O��n��o�f�sg)|���g纟ވl�;4���tMژ�F�y��E�s�ڰ����˶O�:ͨ�|���^�mr^"���u���������6 Y����lכVP6���ǫ$��-��p�O#~�߽�������[����zeoe����������ѥ�)ܣ�����+����W�o��ڒ���vJ{���}E�??�1X�+vF�<�,�ͺb� �;gf��ӣV����;�;����g��çk �)EӮH�����O>|;��T��E�0mK;,)�{A�U���߿Q�FyÛoK�۵���;��e����P�WNhݮ�f
DEBUG:avs.alexa:metadata: {
"event": {
"header": {
"namespace": "System",
"name": "SynchronizeState",
"messageId": "65a2d68cece747bd8b4f0fa40936e073"
},
"payload": {}
},
"context": [
{
"header": {
"namespace": "SpeechSynthesizer",
"name": "SpeechState"
},
"payload": {
"token": "",
"playerActivity": "FINISHED",
"offsetInMilliseconds": 0
}
},
{
"header": {
"namespace": "Speaker",
"name": "VolumeState"
},
"payload": {
"volume": 50,
"muted": false
}
},
{
"header": {
"namespace": "AudioPlayer",
"name": "PlaybackState"
},
"payload": {
"token": "",
"playerActivity": "IDLE",
"offsetInMilliseconds": 0
}
},
{
"header": {
"namespace": "Alerts",
"name": "AlertsState"
},
"payload": {
"allAlerts": [],
"activeAlerts": []
}
}
]
}
INFO:avs.alexa:wait for response
DEBUG:hyper.http20.connection:recv for stream 3 with set([1]) already present
%��3�T���ck.hpack:Decoding ������tOK,�fBH�K�DrE�����.1���"��k9#/F�?_Ħ��j�bX��
&=LtA��� ,��,8�!B&~Бؘ)*G �5��D��p/��}��e���u�b
DEBUG:hpack.hpack:Decoded 8, consumed 1 bytes
DEBUG:hpack.hpack:Decoded (':status', '200'), consumed 1
DEBUG:hpack.hpack:Decoded 64, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('access-control-allow-origin', <memory at 0x73eb4f80>), consumed 1
DEBUG:hpack.hpack:Decoded 63, consumed 2 bytes
DEBUG:hpack.hpack:Decoded 44, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('x-amzn-requestid', '06c728fffe3dcd94-00004c6d-0000c350-3d16aba23a82e67b-6d39ad0b-3'), total consumed 47 bytes, indexed True
DEBUG:hpack.hpack:Decoded 31, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 68, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('content-type', 'multipart/related;boundary=------abcde123;start=metadata.1512627619030;type="application/json"'), total consumed 70 bytes, indexed True
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:3, weight:16, depends_on:0, exclusive:False>
INFO:avs.alexa:status code: 200
INFO:avs.alexa:Found 176 bytes of None application/json, first_payload_block=True
INFO:avs.alexa:Finished downloading JSON
DEBUG:avs.alexa:{u'directive': {u'header': {u'namespace': u'System', u'name': u'SetEndpoint', u'messageId': u'cc59261c-59ef-4629-8650-2816e28a37f7'}, u'payload': {u'endpoint': u'https://avs-alexa-eu.amazon.com'}}}
DEBUG:avs.alexa:{
"header": {
"namespace": "System",
"name": "SetEndpoint",
"messageId": "cc59261c-59ef-4629-8650-2816e28a37f7"
},
"payload": {
"endpoint": "https://avs-alexa-eu.amazon.com"
}
}
DEBUG:avs.alexa:ping at Thu Dec 07 11:53:48 2017
INFO:hyper.http20.connection:Received unhandled event 
DEBUG:avs.alexa:ping at Thu Dec 07 11:57:48 2017
DEBUG:avs.alexa:ping at Thu Dec 07 12:01:49 2017

**Comment by Pillar1989** [comment]
Hi, Did  you test sound card ? you need confirm the sound card works fine first.

**Comment by tarunl** [comment]
Can u suggest me a quick way to do the same ?
Though I was able to record and listen through audacity.

**Comment by Pillar1989** [comment]
audacity  is fine.
