### ISSUE TITLE
Noise on the 6 Mic Array audio output

### ISSUE THREAD

**Issue by tomarsnap** [respeaker/seeed-voicecard#171]
The 6mic array audio output has the same amount of noise as the integrated audio out of the Raspberry Pi. There is noticeable crackling whenever data transfer is ongoing for example. Even with an ssh connection I can hear each character typed on the terminal. This is an issue because I would like to use the AEC function of the arrays DAC for voice recognition but if I use an external DAC I will not get the output loopback.

**Comment by jerryyip** [comment]
Hi @tomarsnap, please send us some audio file of the noise and tell us the way you record and play. As we haven't met this issue before, any information will be appreciated.
