### ISSUE TITLE
kernel headers error, Echo error, Don't show in aplay, arecord, alsamixer

### ISSUE THREAD

**Issue by kajo222** [respeaker/seeed-voicecard#175]
pi@raspberrypi:~/seeed-voicecard $ sudo ./install.sh 6mic
Stary:1 http://archive.raspberrypi.org/debian stretch InRelease
Stary:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
All packages are up to date.
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
raspberrypi-kernel is already the newest version (1.20190819~stretch-1).
raspberrypi-kernel-headers is already the newest version (1.20190819~stretch-1).
Następujący pakiet został zainstalowany automatycznie i nie jest już więcej wymagany:
  realpath
Aby go usunąć należy użyć "sudo apt autoremove".
0 aktualizowanych, 0 nowo instalowanych, 0 usuwanych i 0 nieaktualizowanych.
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
dkms is already the newest version (2.3-2).
git is already the newest version (1:2.11.0-3+deb9u4).
i2c-tools is already the newest version (3.1.2-3).
libasound2-plugins is already the newest version (1.1.1-1).
Następujący pakiet został zainstalowany automatycznie i nie jest już więcej wymagany:
  realpath
Aby go usunąć należy użyć "sudo apt autoremove".
0 aktualizowanych, 0 nowo instalowanych, 0 usuwanych i 0 nieaktualizowanych.

-------- Uninstall Beginning --------
Module:  seeed-voicecard
Version: 0.3
Kernel:  4.19.66+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

snd-soc-wm8960.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.66+/
/usr/sbin/dkms: linia 1714: cd: /lib/modules/4.19.66+: Nie ma takiego pliku ani katalogu
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

snd-soc-ac108.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.66+/
/usr/sbin/dkms: linia 1714: cd: /lib/modules/4.19.66+: Nie ma takiego pliku ani katalogu
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

snd-soc-seeed-voicecard.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.66+/
/usr/sbin/dkms: linia 1714: cd: /lib/modules/4.19.66+: Nie ma takiego pliku ani katalogu
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...(bad exit status: 1)

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  seeed-voicecard
Version: 0.3
Kernel:  4.19.66-v7+ (armv7l)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

snd-soc-wm8960.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.66-v7+/kernel/sound/soc/codecs/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

snd-soc-ac108.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.66-v7+/kernel/sound/soc/codecs/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

snd-soc-seeed-voicecard.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.66-v7+/kernel/sound/soc/bcm/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

------------------------------
Deleting module version: 0.3
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->
                 /usr/src/seeed-voicecard-0.3

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.19.66+ cannot be found at
/lib/modules/4.19.66+/build or /lib/modules/4.19.66+/source.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.19.66-v7+ -C /lib/modules/4.19.66-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build............
cleaning build area....

DKMS: build completed.

snd-soc-wm8960:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7+/kernel/sound/soc/codecs/

snd-soc-ac108.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7+/kernel/sound/soc/codecs/

snd-soc-seeed-voicecard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7+/kernel/sound/soc/bcm/

depmod...

DKMS: install completed.
Error! echo
Your kernel headers for kernel 4.19.66-v7l+ cannot be found at
/lib/modules/4.19.66-v7l+/build or /lib/modules/4.19.66-v7l+/source.
mkdir: nie można utworzyć katalogu „/etc/voicecard”: Plik istnieje
git init
Reinitialized existing Git repository in /etc/voicecard/.git/
git add --all
git commit -m "origin configures"
On branch master
nothing to commit, working tree clean
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Enjoy!
------------------------------------------------------

pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~ $ cat /var/log/seeed-voicecard.log 
+ dtparam i2c_arm=on
No protocol specified
+ modprobe i2c-dev
+ dtparam spi=on
No protocol specified
No protocol specified
+ _VER_RUN=
+ CONFIG=/boot/config.txt
++ i2cdetect -y 1 0x1a 0x1a
++ egrep '(1a|UU)'
++ awk '{print $2}'
+ is_1a=UU
++ egrep '(35|UU)'
++ awk '{print $2}'
++ i2cdetect -y 1 0x35 0x35
+ is_35=UU
++ i2cdetect -y 1 0x3b 0x3b
++ awk '{print $2}'
++ egrep '(3b|UU)'
+ is_3b=UU
+ RPI_HATS='seeed-2mic-voicecard seeed-4mic-voicecard seeed-8mic-voicecard'
+ overlay=
+ '[' xUU '!=' x ']'
+ '[' xUU == x ']'
+ '[' xUU '!=' x ']'
+ '[' xUU == x ']'
+ '[' xUU '!=' x ']'
+ '[' xUU '!=' x ']'
+ echo 'install 6mic'
install 6mic
+ overlay=seeed-8mic-voicecard
+ asound_conf=/etc/voicecard/asound_6mic.conf
+ asound_state=/etc/voicecard/ac108_6mic.state
+ '[' seeed-8mic-voicecard ']'
+ echo Install seeed-8mic-voicecard ...
Install seeed-8mic-voicecard ...
+ rm /etc/asound.conf
+ rm /var/lib/alsa/asound.state
++ get_kernel_version
++ local ZIMAGE IMG_OFFSET
++ _VER_RUN=
++ '[' -z '' ']'
++ ZIMAGE=/boot/kernel.img
+++ LC_ALL=C
+++ grep -abo $'\037\213\b' /boot/kernel.img
+++ head -n 1
+++ cut -d : -f 1
++ IMG_OFFSET=18092
+++ dd if=/boot/kernel.img obs=64K ibs=4 skip=4523
+++ zcat
+++ grep -a -m1 'Linux version'
+++ awk '{ print $3; }'
+++ strings

gzip: stdout: Broken pipe
dd: zapis do 'standardowe wyjście': Przerwany potok
933888+0 przeczytanych rekordów
56+0 zapisanych rekordów
3670016 bajtów (3,7 MB, 3,5 MiB), 7,47978 s, 491 kB/s
++ _VER_RUN=4.19.66+
++ echo 4.19.66+
++ return 0
+ kernel_ver=4.19.66+
+ [[ 4.19.66+ =~ ^4\.19.*$ ]]
+ for i in $RPI_HATS
+ '[' seeed-2mic-voicecard == seeed-8mic-voicecard ']'
+ echo Uninstall seeed-2mic-voicecard ...
Uninstall seeed-2mic-voicecard ...
+ do_overlay seeed-2mic-voicecard 1
+ ov=seeed-2mic-voicecard
+ RET=1
+ DEFAULT=--defaultno
+ CURRENT=0
++ get_overlay seeed-2mic-voicecard
++ ov=seeed-2mic-voicecard
++ grep -q -E '^dtoverlay=seeed-2mic-voicecard' /boot/config.txt
++ echo 1
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 1 ']'
+ sed /boot/config.txt -i -e 's/^dtoverlay=seeed-2mic-voicecard/#dtoverlay=seeed-2mic-voicecard/'
+ STATUS=disabled
+ for i in $RPI_HATS
+ '[' seeed-4mic-voicecard == seeed-8mic-voicecard ']'
+ echo Uninstall seeed-4mic-voicecard ...
Uninstall seeed-4mic-voicecard ...
+ do_overlay seeed-4mic-voicecard 1
+ ov=seeed-4mic-voicecard
+ RET=1
+ DEFAULT=--defaultno
+ CURRENT=0
++ get_overlay seeed-4mic-voicecard
++ ov=seeed-4mic-voicecard
++ grep -q -E '^dtoverlay=seeed-4mic-voicecard' /boot/config.txt
++ echo 1
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 1 ']'
+ sed /boot/config.txt -i -e 's/^dtoverlay=seeed-4mic-voicecard/#dtoverlay=seeed-4mic-voicecard/'
+ STATUS=disabled
+ for i in $RPI_HATS
+ '[' seeed-8mic-voicecard == seeed-8mic-voicecard ']'
+ do_overlay seeed-8mic-voicecard 0
+ ov=seeed-8mic-voicecard
+ RET=0
+ DEFAULT=--defaultno
+ CURRENT=0
++ get_overlay seeed-8mic-voicecard
++ ov=seeed-8mic-voicecard
++ grep -q -E '^dtoverlay=seeed-8mic-voicecard' /boot/config.txt
++ echo 0
+ '[' 0 -eq 0 ']'
+ DEFAULT=
+ CURRENT=1
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 0 ']'
+ sed /boot/config.txt -i -e 's/^#dtoverlay=seeed-8mic-voicecard/dtoverlay=seeed-8mic-voicecard/'
+ grep -q -E '^dtoverlay=seeed-8mic-voicecard' /boot/config.txt
+ STATUS=enabled
+ dtoverlay seeed-8mic-voicecard
No protocol specified
* Failed to apply overlay '2_seeed-8mic-voicecard' (kernel)
No protocol specified
+ true
+ echo 'create seeed-8mic-voicecard asound configure file'
create seeed-8mic-voicecard asound configure file
+ ln -s /etc/voicecard/asound_6mic.conf /etc/asound.conf
+ echo 'create seeed-8mic-voicecard asound status file'
create seeed-8mic-voicecard asound status file
+ ln -s /etc/voicecard/ac108_6mic.state /var/lib/alsa/asound.state
+ alsactl restore
Found hardware: "bcm2835_alsa" "Broadcom Mixer" "" "" ""
Hardware is initialized using a generic method
alsactl: set_control:1325: failed to obtain info for control #6 (No such file or directory)
+ amixer cset numid=3 1
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=3,step=0
  : values=1

pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- UU -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- UU -- -- -- -- -- UU -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --   

I tried removing, reinstalling the kernel, modifying the install.sh file to manually write the kernel, Different versions of the system (even 2 years older), modify /boot/config.txt, restart the seeed service. I tested with apt-get upgrade and without. I tried to manually copy files to version}/kernel/sound/soc/codecs. I have Respeaker 6mic and Raspberry pi 3

Please Help me

**Comment by Pillar1989** [comment]
I suggest you test the hardware and our software with an lastest system.

**Comment by kajo222** [comment]
I do it and don't work

czw., 22 sie 2019 o 03:06 Baozhu Zuo <notifications@github.com> napisał(a):

**Comment by Pillar1989** [comment]
![image](https://user-images.githubusercontent.com/4081906/63489874-e03a9000-c4e5-11e9-8190-c3c7cc463fb8.png)
Did you delete it?

**Comment by kajo222** [comment]
no

czw., 22 sie 2019 o 08:05 Baozhu Zuo <notifications@github.com> napisał(a):

**Comment by Pillar1989** [comment]
Show me. I don't believe it.

**Comment by kajo222** [comment]
kacper@kacper-INVALID:~$ sudo ssh pi@10.10.0.59
pi@10.10.0.59's password: 
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Aug 22 10:06:27 2019

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~ $ ls
4.19.66+      Desktop    Downloads  Music     Public           Templates
4.19.66-v7l+  Documents  MagPi      Pictures  seeed-voicecard  Videos
pi@raspberrypi:~ $ cd seeed-voicecard/
pi@raspberrypi:~/seeed-voicecard $ ls /lib/mod
modprobe.d/ modules/    
pi@raspberrypi:~/seeed-voicecard $ ls /lib/modules/
4.19.66-v7+
pi@raspberrypi:~/seeed-voicecard $ sudo ./install.sh 6mic
Stary:1 http://archive.raspberrypi.org/debian buster InRelease
Stary:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
All packages are up to date.
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
raspberrypi-kernel is already the newest version (1.20190819-1).
Następujące pakiety zostały zainstalowane automatycznie i nie są już więcej wymagane:
  python3-pyperclip python3-thonny rpi.gpio-common
Aby je usunąć należy użyć "sudo apt autoremove".
Zostaną zainstalowane następujące NOWE pakiety:
  raspberrypi-kernel-headers
0 aktualizowanych, 1 nowo instalowanych, 0 usuwanych i 0 nieaktualizowanych.
Konieczne pobranie 24,9 MB archiwów.
Po tej operacji zostanie dodatkowo użyte 163 MB miejsca na dysku.
Pobieranie:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20190819-1 [24,9 MB]
Pobieranie:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20190819-1 [24,9 MB]
Pobrano 3 207 kB w 19s (173 kB/s)                                              
Wybieranie wcześniej niewybranego pakietu raspberrypi-kernel-headers.
(Odczytywanie bazy danych ... 91923 pliki i katalogi obecnie zainstalowane.)
Przygotowywanie do rozpakowania pakietu .../raspberrypi-kernel-headers_1.20190819-1_armhf.deb ...
Rozpakowywanie pakietu raspberrypi-kernel-headers (1.20190819-1) ...
Konfigurowanie pakietu raspberrypi-kernel-headers (1.20190819-1) ...
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
git is already the newest version (1:2.20.1-2).
i2c-tools is already the newest version (4.1-1).
i2c-tools zaznaczony jako zainstalowany ręcznie.
Następujące pakiety zostały zainstalowane automatycznie i nie są już więcej wymagane:
  python3-pyperclip python3-thonny rpi.gpio-common
Aby je usunąć należy użyć "sudo apt autoremove".
Sugerowane pakiety:
  python3-apport menu
Zostaną zainstalowane następujące NOWE pakiety:
  dkms libasound2-plugins
0 aktualizowanych, 2 nowo instalowanych, 0 usuwanych i 0 nieaktualizowanych.
Konieczne pobranie 139 kB archiwów.
Po tej operacji zostanie dodatkowo użyte 565 kB miejsca na dysku.
Pobieranie:1 http://ftp.icm.edu.pl/pub/Linux/distributions/raspbian/raspbian buster/main armhf dkms all 2.6.1-4 [74,4 kB]
Pobieranie:2 http://ftp.icm.edu.pl/pub/Linux/distributions/raspbian/raspbian buster/main armhf libasound2-plugins armhf 1.1.8-1 [64,2 kB]
Pobrano 139 kB w 1s (220 kB/s)           
Wybieranie wcześniej niewybranego pakietu dkms.
(Odczytywanie bazy danych ... 142482 pliki i katalogi obecnie zainstalowane.)
Przygotowywanie do rozpakowania pakietu .../archives/dkms_2.6.1-4_all.deb ...
Rozpakowywanie pakietu dkms (2.6.1-4) ...
Wybieranie wcześniej niewybranego pakietu libasound2-plugins:armhf.
Przygotowywanie do rozpakowania pakietu .../libasound2-plugins_1.1.8-1_armhf.deb ...
Rozpakowywanie pakietu libasound2-plugins:armhf (1.1.8-1) ...
Konfigurowanie pakietu libasound2-plugins:armhf (1.1.8-1) ...
Konfigurowanie pakietu dkms (2.6.1-4) ...
Przetwarzanie wyzwalaczy pakietu man-db (2.8.5-2)...

Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->
                 /usr/src/seeed-voicecard-0.3

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.19.66+ -C /lib/modules/4.19.66+/build M=/var/lib/dkms/seeed-voicecard/0.3/build.......
cleaning build area.....

DKMS: build completed.

snd-soc-wm8960.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66+/kernel/sound/soc/codecs/

snd-soc-ac108.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66+/kernel/sound/soc/codecs/

snd-soc-seeed-voicecard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66+/kernel/sound/soc/bcm/

depmod...

DKMS: install completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.19.66-v7+ -C /lib/modules/4.19.66-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build.......
cleaning build area.....

DKMS: build completed.

snd-soc-wm8960.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7+/kernel/sound/soc/codecs/

snd-soc-ac108.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7+/kernel/sound/soc/codecs/

snd-soc-seeed-voicecard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7+/kernel/sound/soc/bcm/

depmod.....

DKMS: install completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.19.66-v7l+ -C /lib/modules/4.19.66-v7l+/build M=/var/lib/dkms/seeed-voicecard/0.3/build......
cleaning build area.....

DKMS: build completed.

snd-soc-wm8960.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7l+/kernel/sound/soc/codecs/

snd-soc-ac108.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7l+/kernel/sound/soc/codecs/

snd-soc-seeed-voicecard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.66-v7l+/kernel/sound/soc/bcm/

depmod...

DKMS: install completed.
setup git config
git init
Initialized empty Git repository in /etc/voicecard/.git/
git add --all
git commit -m "origin configures"
[master (root-commit) 3999dd1] origin configures
 7 files changed, 1476 insertions(+)
 create mode 100644 ac108_6mic.state
 create mode 100644 ac108_asound.state
 create mode 100644 asound_2mic.conf
 create mode 100644 asound_4mic.conf
 create mode 100644 asound_6mic.conf
 create mode 100644 dkms.conf
 create mode 100644 wm8960_asound.state
Created symlink /etc/systemd/system/sysinit.target.wants/seeed-voicecard.service → /lib/systemd/system/seeed-voicecard.service.
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Enjoy!
------------------------------------------------------
pi@raspberrypi:~/seeed-voicecard $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~/seeed-voicecard $ sudo reboot
Connection to 10.10.0.59 closed by remote host.
Connection to 10.10.0.59 closed.
kacper@kacper-INVALID:~$ sudo ssh pi@10.10.0.59
pi@10.10.0.59's password: 
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Aug 22 10:19:39 2019

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
pi@raspberrypi:~ $ sudo service seeed-voicecard restart
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
pi@raspberrypi:~ $

**Comment by kajo222** [comment]
On the latest image i don't have that problem, but still don't work

**Comment by kajo222** [comment]
Installed your preconfigured image and working, but i want know why before don't work

**Comment by kajo222** [comment]
And after preconfig and raspi-config again don't work

czw., 22 sie 2019 o 09:45 Baozhu Zuo <notifications@github.com> napisał(a):

**Comment by kajo222** [comment]
i dont update btw

czw., 22 sie 2019 o 09:18 Kacper korczak <kacper.korczak123@gmail.com>
napisał(a):

**Comment by kajo222** [comment]
I think it is 1-Wire problem, how i can use 1-wire and respeaker?

**Comment by Pillar1989** [comment]
the  issue fixed?

**Comment by kajo222** [comment]
YEAH

wt., 3 wrz 2019, 08:05 użytkownik Baozhu Zuo <notifications@github.com>
napisał:

**Comment by Pillar1989** [comment]
So let me close the issue, I hope you can come and communicate with us next time you encounter problems. I sincerely hope you are in good health and everything goes well.
