### ISSUE TITLE
respeaker and beaglebone

### ISSUE THREAD

**Issue by tulptuiz** [respeaker/seeed-voicecard#178]
Hi, I want to install drivers and run respeaker-4-mic array on Beaglebone Green with Debian, but I have some problems with integration. 
If there is any posssibility to install it on armhf debian? 
Or do these driviers works only with Raspbian?   
Thanks in advance

**Comment by Pillar1989** [comment]
@tulptuiz  https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/seeed-4mic-voicecard-00A0.dts
wellcom to test
