### ISSUE TITLE
[REQUEST] Drivers for Jetson Nano

### ISSUE THREAD

**Issue by Gleb-ko** [respeaker/seeed-voicecard#179]
I think ReSpeaker products are great and I want to use one of the GPIO hats with a Jetson Nano; however, I can see that there are only drivers for the Raspberry Pi. Are there any plans of making drivers for the Jetson Nano?

**Comment by Pillar1989** [comment]
We are internally porting it to the Jetson Nano platform, so keep an eye on our project for the latest information

**Comment by Gleb-ko** [comment]
Ok, thank you for the information

**Comment by testforpepper** [comment]
Hi, just wanted to ask if they've already been added? Cheers!
