### ISSUE TITLE
Support driver for AndroidThings OS 

### ISSUE THREAD

**Issue by vu111293** [respeaker/seeed-voicecard#18]
When is there the 2mic board' driver for AndroidThings?

**Comment by Pillar1989** [comment]
For AndroidThings. Welcome for PR.

**Comment by vu111293** [comment]
Dear Pillar1989,

When I use respeaker 2mic for AndroidThings, then not working. 
How to use for AndroidThings?

**Comment by Pillar1989** [comment]
#13

**Comment by Pillar1989** [comment]
#13 Please refer to this issue
