### ISSUE TITLE
Not working on 4.19.71+ - Respeaker 2 and 6 mic array - RPi 3 and RPi 3B+

### ISSUE THREAD

**Issue by vedranius** [respeaker/seeed-voicecard#180]
I'm getting a problem for kernel 4.19.71+ for Respeaker 2 and 6 mic array - RPi 3 and RPi 3B+

Can you fix it?!

 !!! Your kernel version is 4.19.71+
     Not found *** coressponding *** kernel headers with apt-get.
     This may occur if you have ran 'rpi-update'.
 Choose  *** y *** will revert the kernel to version 4.19.66+ then continue.
 Choose  *** N *** will exit without this driver support, by default.

**Comment by Pillar1989** [comment]
@vedranius  Problem solved? Next time you ask a question remember to describe clearly, otherwise it will be easy to ignore.

**Comment by Nokius** [comment]
@Pillar1989 it's the same issue as in #183 The newer kernel is not supported.

**Comment by HinTak** [comment]
if you do apt upgrade now, it should all work. See https://github.com/raspberrypi/linux/issues/3279

**Comment by turmary** [comment]
Will close this issue, please open a new issue if you have further questions.
