### ISSUE TITLE
Noise artefacts in  the sound output using the default configuration.

### ISSUE THREAD

**Issue by cpoisson** [respeaker/seeed-voicecard#188]
Hi,

I have observed some noises artefacts (Pop and clicks) when using the default configuration.

I use a raspbian stretch on a raspberry Pi 3 with the following boards:
- [PiHAT 2 Mics](https://www.seeedstudio.com/ReSpeaker-2-Mics-Pi-HAT.html)
- [Respeaker 6 Mics](http://wiki.seeedstudio.com/ReSpeaker_6-Mic_Circular_Array_kit_for_Raspberry_Pi/)

Commenting the resampling configuration in `/etc/asound.conf` seems to fix the problem.

```
# use samplerate to resample as speexdsp resample is broken
# defaults.pcm.rate_converter "samplerate"
```

**Comment by Pillar1989** [comment]
Is it? We didn't find the abnormality you mentioned.  Different resampling will only change the frequency response

**Comment by cpoisson** [comment]
I noticed this behaviour on multiple Snips Maker kit (the one using the piHAT 2 Mics) using our audio-server (snipsco/snips-issues#198)

It may be a specific SW configuration / snips-audio-server issue with the resampling.
Let's close this one.
