### ISSUE TITLE
Cannot detect device after recent system update.

### ISSUE THREAD

**Issue by VirosaLi** [respeaker/seeed-voicecard#189]
I'm using the 6 mic array for pi with Pi 4. I updated the system by 'apt upgrade'.  Then the pi couldn't detect the mic array anymore.

**Comment by HinTak** [comment]
probably the same issue as https://github.com/respeaker/seeed-voicecard/issues/190

**Comment by HinTak** [comment]
If you do apt upgrade now it should work. See https://github.com/raspberrypi/linux/issues/3279

**Comment by VirosaLi** [comment]
Yep, the problem is solved after the upgrade.
