### ISSUE TITLE
Mic-3 is muted in 6-mic and 4-mic array

### ISSUE THREAD

**Issue by giancarlocp** [respeaker/seeed-voicecard#194]
Testing the 6-Mic Circular and 4-Mic Linear array,
In both cases I have noticed the mic 3 is muted.
I am working in a **Raspberry Pi 3 B+** and
**Raspbian Buster** with **Linux 4.19.75-v7+ armv7l**

**Comment by Pillar1989** [comment]
This should be the hardware is broken, please try other @giancarlocp

**Comment by HinTak** [comment]
@giancarlocp : this is probably the same issue as https://github.com/respeaker/seeed-voicecard/issues/240 - the seeedvoice card systemd service assumes that the on-board bcm driver is loaded, and set playback audio to the on-board phone jack with a amixer command. Unforturnately, if you don't use the pi's on-board audio (or with a later kernel where they are separate), the amixer command when applied to the wrong device, has the effect of turning the recording volume of the 3rd channel really low!
