### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by simonmaurer** [respeaker/seeed-voicecard#195]
after checking an older post [https://github.com/respeaker/seeed-voicecard/issues/94](url) with a similar question: any updates regarding Android integration for the Respeaker boards..?

is there a chance to get the Respeaker ie. [ReSpeaker 4-mic array](http://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/)
 working on an Android image ?

**Comment by Pillar1989** [comment]
Sorry, Android OS isn't on raspberry PI's website
