### ISSUE TITLE
poor speech recognition with python stt

### ISSUE THREAD

**Issue by Kuldeepwadaskar** [respeaker/seeed-voicecard#197]
hello, i have setup respeaker with raspberry pi and now i am trying to do speech to text with python but re-speaker speech listening is poor, it records audio in good quality but when it is used with speech to text then range is very narrow, do not listen correct world, need to repeat words and need to shout to make it here you..

is there any internal setting to increase re speaker mic and SST quality?
respeaker:- 4 mic array
hardware: raspberry pi
programming lang : python simple speech to text.

**Comment by Pillar1989** [comment]
This problem, we can't help you, the fundamental problem is not above the hardware and driver
