### ISSUE TITLE
ReSpeaker 4-Mic Linear Array - noise detection problems

### ISSUE THREAD

**Issue by julia100009** [respeaker/seeed-voicecard#199]
Hallo,
I have installed the ReSpeaker 4-Mic Linear Array Kit for Raspberry P (4 Model Rev 1.1) as shown on the seeed website (seeed-8mic-voicecard). 
I have programmed an AI that detects noises. Everything works perfectly until I restart the Raspberry. Then the noises are no longer recognized.
The following picture shows the same sound before and after the restart.

Does anyone have any idea what the problem is? Is it the AGC? The recording volume is adjusted somehow, how can i change it?

Thank you in advance. Kind regards,
Julia
![Unbenannt](https://user-images.githubusercontent.com/57394061/68199682-cd047000-ffbe-11e9-8748-37a93b0bca1d.JPG)

**Comment by Pillar1989** [comment]
Have you worked it out?

**Comment by julia100009** [comment]
Hi,
I think the problem was AGC. Unfortunately I could not disable AGC on the Model ReSpeaker 4-Mic Linear Array. I bought the model Mic Array v2.0. Now I can adjust the parameters (AGC etc.), the problem is gone.
Thanks for asking.

**Comment by Pillar1989** [comment]
AC108 doesn't have  AGC. This is his  specification.
https://cdn.sparkfun.com/assets/6/0/d/c/a/AC108_Datasheet_V1.1.pdf

**Comment by Atul-Anand-Jha** [comment]
> Hi,
> I think the problem was AGC. Unfortunately I could not disable AGC on the Model ReSpeaker 4-Mic Linear Array. I bought the model Mic Array v2.0. Now I can adjust the parameters (AGC etc.), the problem is gone.
> Thanks for asking.

@julia100009  ,How did you adjusted the AGC ? I am also unable to activate BF( beam Forming) . How to do these stuffs.
