### ISSUE TITLE
4 channel cut off

### ISSUE THREAD

**Issue by Tectea** [respeaker/seeed-voicecard#201]
When recording 4 channels using "arecord -D ac108 -f S32_LE -r 96000 -c 4 test.wav" the amplitude gets cut off compared to the same input sound using 1 channel. 

Perhaps this is a limit in arecord instead of seeed-voicecard. Using ReSpeaker linear 4 channel card.

**Comment by Pillar1989** [comment]
You set the volume too high

**Comment by Tectea** [comment]
Thank toy Pillar1989 for the comment. I tried adjusting the capture volume through alsamixer and it works great!
