### ISSUE TITLE
AC108 I2C specification

### ISSUE THREAD

**Issue by andre-stefanov** [respeaker/seeed-voicecard#203]
Hello,

I am trying to get the Respeaker 4-Mic RPi hat array running with an microcontroller based project. Unfortunatelly the AC108 documentation lacks information about the I2C interface. I see that @Pillar1989 has implemented this as a kernel driver for raspberry pi. Is it possible to provide the AC108 documentation together with the board docs (e.g. in the Wiki). Or could someone point me into the right direction please (before i start to reverse engineer the kernel driver). Thank you in advance!

**Comment by Pillar1989** [comment]
Regarding AC108's i2c register manual, x-powers does not authorize open access for all persons.If it can be opened up, we are very willing to share with you.
