### ISSUE TITLE
Combine ReSpeaker 2-mic with LCD display

### ISSUE THREAD

**Issue by stefan-reich** [respeaker/seeed-voicecard#208]
Hi, is there a way to combine these in one Raspberry Pi 3B?

[Display I use](https://www.ebay.de/itm/3-5-320-480-TFT-Touchscreen-LCD-Display-fur-Raspberry-Pi-A-B-A-2B-3B-3-Hz/174082218711)

**Comment by Pillar1989** [comment]
You can't do that.
