### ISSUE TITLE
Recording not working

### ISSUE THREAD

**Issue by bshogeman** [respeaker/seeed-voicecard#21]
arecord -Dac108 -f S32_LE -r 16000 -c 4 a.wav -d 10
arecord: main:788: audio open error: File or folder doesn't exist

The pixel ring is working with the example files. Only can't seem to get the mic's working on the ReSpeaker 4mic model.

What can I do to fix this?

**Comment by Pillar1989** [comment]
Hi , Where do you want to store the a.wav ?  maybe you can try 
`arecord -Dac108 -f S32_LE -r 16000 -c 4  /tmp/a.wav -d 10`

**Comment by bshogeman** [comment]
In the home folder. The writing of the file isn't the problem. If I skip the -Dac108 and -f S32_LE parameters the command (not specify the soundcard or just the command for the 2mic version) is working and writes a file. Only the file doesn't create anything but a long silence.

**Comment by Pillar1989** [comment]
which pi image do you use ?

**Comment by bshogeman** [comment]
Raspberry Pi 3 B

**Comment by Pillar1989** [comment]
#25
