### ISSUE TITLE
Set default HDMI audio output

### ISSUE THREAD

**Issue by lcarado** [respeaker/seeed-voicecard#215]
Hi,
I have a RPi 4 with fresh raspian istalled (Buster) with 4-Mics Linear Array kit, no other software istalled.

I Install the seeed-voicecard driver for the 4-Mics with this istructions [http://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/](url) and all was fine.

All audio input and outputs are working, I can select the output from the volume panel on the bar and I can record from 4-Mics.
Normally I hear audio from HDMI monitor connected on HDMI0 port.

Here aplay and arecord list:

> pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: seeed8micvoicec [seeed-8mic-voicecard], device 0: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-0035-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

> pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed8micvoicec [seeed-8mic-voicecard], device 0: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-0035-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ 

Raspian version:
`pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU`

My problem start when I restart the RPi because the audio output switch to analog.
I manually switch to HDMI from the volume panel and all works fine but when I restart the audio switch again on analog output.
I tried set audio output on HDMI from `raspi-config` and with `amixer cset numid=3 2` and also with `hdmi_drive=2` in config.txt but when I restart the audio return on analog.

As a last chance I unistall the seeed-voicecard driver (`./unistall.sh`), I restart  and ... miracle, the audio output is on HDMI!!!
Why does this driver force audio output to analog?
Does anyone know how to permanently set the audio output to HDMI with seeed-voicecard driver istalled?
Thanks for any help

**Comment by Daenara** [comment]
I use an external USB soundcard and it overwrites my settings also. After quite a while of googeling I found a file /etc/asound.conf which seems to be responsible for the sound config (at least on my RPi3).

`pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "ac108
}

pcm.playback {
    type plug
    slave.pcm "hw:1,0"
}`

That is the relevant part of the config (manually typed, not copied). In the pcm.playback part it was hw:ALSA before I changed it. Not sure if it is the recommended way but after I changed that part to the hardware id (or something, not really a linux person) of my sound card it is the default playback device.

**Comment by l-carado** [comment]
Many thanks for your suggestion Daenara,
in these days I studied the wiki of Alsa Project but is very difficult.
I install a fresh raspian and I don't found any /etc/asound.conf file but the audio works perfectly.
The RPi4 start on HDMI 0 output and I can switch analog and HDMI from the volume plugin on the bar.
When I install the reaspeker driver, when I restart the RPi4, the audio is always set on analog output not on HDMI.
I can always switch the output from the plugin.
After that I found an /etc/asound.conf file that is exactly the same of asound_6mic.conf in this project 
([https://github.com/respeaker/seeed-voicecard/blob/master/asound_6mic.conf](https://github.com/respeaker/seeed-voicecard/blob/master/asound_6mic.conf))

In the pi folder I found also the .asoundrc.conf file:

```
pcm.!default {
	type asym
	playback.pcm {
		type plug
		slave.pcm "output"
	}
	capture.pcm {
		type plug
		slave.pcm "input"
	}
}

pcm.output {
	type hw
	card 0
	device 1 <--- added by me
}

ctl.!default {
	type hw
	card 0
}
```

I try to add the row "device 1" in the pcm.output section to switch the audio on HDMI 0 output but nothing change.
I think RPi4 works in different way.
Do you know other way to set permanently the audio on HDMI?
Do you know how the volume plugin switch the output?
Thanks

lcarado

**Comment by HinTak** [comment]
@lcarado well, you have found the answer yourself - see comment in https://github.com/HinTak/seeed-voicecard/commit/a5095cd7b2e43b528bb9e3b82c539f265685d008 - in summary, you need to edit `/usr/bin/seeed-voicecard` to stop it resetting to headphone jack output.

**Comment by HinTak** [comment]
It is interesting that between 4.19.75 you have and 4.19.118 I am using in later Raspbian in one of my SD cards, the routing option was removed - ie on later Raspbian you do not redirect audio playback - each device is usable for playback independently and simultaneously.
