### ISSUE TITLE
Respeaker 2 Mic Hat Not working properly in Buster

### ISSUE THREAD

**Issue by shivasiddharth** [respeaker/seeed-voicecard#219]
The speaker and the 3.5mm jack on the Respeaker 2 Mic Hat do not work when the Hat's microphone is open.

How to replicate:
Open one terminal and run:
 `arecord -f S16_LE -d 20 -r 16000 --channels 2 --device="hw:seeed2micvoicec" /tmp/test-mic.wav`

Open second terminal and run:
`speaker-test -t wav`

**Comment by pascaltippelt** [comment]
I confirm this problem. Only Mic or Speaker works - but both together dont.

**Comment by Pillar1989** [comment]
@pascaltippelt  @shivasiddharth  Can you describe the usage scenario in detail?

**Comment by shivasiddharth** [comment]
Usage scenario is Google Assistant SDK and Alexa Voice SDK

**Comment by shivasiddharth** [comment]
@Pillar1989 This issue occurs if pulseaudio is installed. Just to clarify.
