### ISSUE TITLE
Error: Not enough space left (20M) on /boot

### ISSUE THREAD

**Issue by d3-worgan** [respeaker/seeed-voicecard#226]
Hi,

I have formatted an SD card, installed raspian stretch lite, and then followed the steps to install the seeed drivers for the 4mic array. Unfortunately I get the error:

```
Error: Not enough space left (20M) on /boot
```
when I run

```
sudo ./install.sh
```

How much space is needed? Why does it need space in boot? Has code in the repo changed or what else would have changed in raspbian stretch do you think?

It used to work following excactly the same steps? Do I need to increase the boot space?

**Comment by HinTak** [comment]
Argh, because it tries to downgrade the kernel... There is an option not to downgrade.

**Comment by Pillar1989** [comment]
https://github.com/respeaker/seeed-voicecard/issues/249

**Comment by turmary** [comment]
Now there is message about lowest /boot space requirement, but not accurate.

**Comment by marxenegls** [comment]
sob i have the same issue i was all giggles 5minute ago  thought my picroft was in the making  : (- now i'm gonna have to copy the sd card partitions .. format and recreate the whole thing anew - is that it . ? 
.wait a min,  but i thought boot partition is around 65Mb , it says it needs 25Mb .. somebody has been greedy, i'm gonna find out who and i'll be putting em on an acetic diet ..first i'll have to decouple shutdown and move to the operating room next door.. I'll let yous know yous guts i ripped out

**Comment by marxenegls** [comment]
found 2 kernel.img + kernel7.img loosing one did it for me in my case the kernel.img since i'm on a pi3
