### ISSUE TITLE
 libasound2-plugins not available in gentoo

### ISSUE THREAD

**Issue by dony71** [respeaker/seeed-voicecard#227]
I manage to install seeed-voicecard-2mic driver manually in  gentoo
Driver module is loaded OK, but since gentoo doesn't have libasound2-plugins, so I install alsa-plugin which has library for re-sample.
But still "aplay xxx.wav" has sound distorted
Any idea for solution?

[I] media-plugins/alsa-plugins
     Available versions:  1.2.1 1.2.2 {arcam_av debug ffmpeg jack libsamplerate +mix oss pulseaudio speex +usb_stream ABI_MIPS="n32 n64 o32" ABI_RISCV="lp64 lp64d" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  1.2.2(07:51:48 PM 05/04/2020)(mix pulseaudio usb_stream -arcam_av -debug -ffmpeg -jack -libsamplerate -oss -speex ABI_MIPS="-n32 -n64 -o32" ABI_RISCV="-lp64 -lp64d" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            http://www.alsa-project.org/
     Description:         ALSA extra plugins

**Comment by Pillar1989** [comment]
The question seems to have no relation with us.
