### ISSUE TITLE
Unable to install 6-mic driver on RT kernel (4.19.71-rt24)

### ISSUE THREAD

**Issue by gits00** [respeaker/seeed-voicecard#229]
Hello all,

I am trying to use the "ReSpeaker 6-Mic Circular Array kit" on RT kernel from https://github.com/raspberrypi/linux/tree/rpi-4.19.y-rt (currently at 4.19.71-rt24). To do the compilation, followed the "Local building" steps mentioned at https://www.raspberrypi.org/documentation/linux/kernel/building.md

On this kernel after running sudo ./install.sh, I am getting error -
 
seeed-voicecard soc: sound: prop pinctrl-0 index 0 invalid phandle
This is with the dtbo from the github

Next, I tried running the "builddtbo.sh" to regenerate dtbos again. Before running, made a change in "builddtbo.sh"  to use "/usr/bin/dtc" OR "dtc" from the newly compiled kernel. In both cases got errors- 

seeed-voicecard soc: sound: seeed_voice_card_dai_link_of: Can't find seeed-voice-card, cpu DT node 

How to go about installing this driver?

**Comment by Pillar1989** [comment]
I'm sorry that we have not tested RT kernel, so we can't help you. I'm really sorry.
