### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by DerT94** [respeaker/seeed-voicecard#232]
Hello,

I have used "sudo ./install.sh --compat-kernel" and it works.
But when I use "sudo apt-get upgrade" to update my packages, the kernel is also updated and the microphone is no longer functional.

**Comment by HinTak** [comment]
See https://github.com/respeaker/seeed-voicecard/issues/231#issuecomment-661723870

**Comment by DerT94** [comment]
thank you.
That works
