### ISSUE TITLE
Failed to start Seeed Voicecard service.

### ISSUE THREAD

**Issue by wzr6009** [respeaker/seeed-voicecard#243]
![_P_9_5UK}A%CIKS4J(0FG3N](https://user-images.githubusercontent.com/56337456/90971232-58e08c00-e540-11ea-8f30-443761819ad9.png)
● seeed-voicecard.service - Seeed Voicecard service
   Loaded: loaded (/lib/systemd/system/seeed-voicecard.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-23 08:37:00 CST; 4h 5min ago
 Main PID: 362 (code=exited, status=1/FAILURE)

8月 23 08:36:46 raspberrypi systemd[1]: Starting Seeed Voicecard service...
8月 23 08:36:47 raspberrypi seeed-voicecard[362]: + exec
8月 23 08:36:47 raspberrypi seeed-voicecard[362]: ++ basename /usr/bin/seeed-voicecard
8月 23 08:37:00 raspberrypi systemd[1]: seeed-voicecard.service: Main process exited, code=exited, status=1/FAILURE
8月 23 08:37:00 raspberrypi systemd[1]: seeed-voicecard.service: Failed with result 'exit-code'.
8月 23 08:37:00 raspberrypi systemd[1]: Failed to start Seeed Voicecard service.

**Comment by TimWolz** [comment]
@HinTak I tried your fork v5.5 for the 4-mic array on the Pi4 with the the 5.4.51-v7l+ kernel. The soundcard is displayed in arecord-L but not found by pyaudio. Any idea what I can do?
Help is greatly appreciated.
![arecord_L](https://user-images.githubusercontent.com/34345962/91305462-62b9f780-e7ab-11ea-8799-b94e83693031.png)
![pyaudio](https://user-images.githubusercontent.com/34345962/91305487-68afd880-e7ab-11ea-8a57-1eef58a5efd6.png)

**Comment by HinTak** [comment]
@TimWolz you have a bug in your python code: why `range(5)`? You need to use a much larger number - and get portfolio to tell you what range. The important thing is, does arecord works? The rest is your python code problem which IMHO belongs elsewhere.

**Comment by HinTak** [comment]
> > 如果您最近升级/安装了新内核，则可能需要v5.5分支https://github.com/HinTak/seeed-voicecard
> 
> I just used the method of reducing the kernel,The sound card is displayed in the aply -l command.
> But there is still no sound when playing a song. The default sound card has been set with alsa.conf 2.
> ![Cache_-2f5ee6258391d8fd](https://user-images.githubusercontent.com/56337456/90974331-cbf7fb80-e55c-11ea-81b8-e62e109b60ab.jpg)
> I use raspberry pi zero

You need to use amixer to adjust the volume... And make sure the playback volume is large enough. This is the same issue as #240

**Comment by HinTak** [comment]
Also the default seeed studio setup (the one that downgrade the kernel) direct the playback to the on-board phone jack. Everything else is silent for playback, I imagine.

Anyway, playback problem does not belong here. Try recording, and transfer the file to yoit desktop for listen if you cannot find out which phone jack to use for listening. There are more than one, and I am sure you got it wrong. Not a driver problem.

**Comment by TimWolz** [comment]
> 
> 
> @TimWolz you have a bug in your python code: why `range(5)`? You need to use a much larger number - and get portaudio to tell you what range. The important thing is, does arecord works? The rest is your python code problem which IMHO belongs elsewhere.

@HinTak  Thanks for your reply. The point why I chose 5 is because there aren't more devices. The same code worked well with the old kernel and the master version. Regarding arecord. I can start it with the default device, which is supposed to be the seeed voicecard but it doesn't terminate, although I specify -d 3. And one cannot replay the (faulty) file. Now, if I also want to specify the device -D seeed4micvoicec, the following error occours ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM seeed4micvoicec

**Comment by HinTak** [comment]
Use the read me - `arecord -Dac108 -f S32_LE -r 16000 -c 4 a.wav` . Wrong pcm device as your error message says.

**Comment by TimWolz** [comment]
Thanks! Sorry thought I have to specify the device name displayed by arecord. But the command from the readme throws the following error:
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
arecord: main:828: audio open error: No such device

**Comment by HinTak** [comment]
@TimWolz I don't know - I only have the 6-mic device and it works okay with either the old kernel with seeed studio upstream, or current 64-bit ubuntu with my fork...

Note also there are two 4-mics devices - one works like a 4-mics, the other works like an 8-mics device with the last few channela empty (i.e. like the 6-mics, but more empty channels). Did you read the wrong section/use the wrong parameters?

**Comment by Pillar1989** [comment]
https://github.com/respeaker/seeed-voicecard/issues/249
