### ISSUE TITLE
Conflict between corbosman/pigpiod install in docker-container and re-speaker 2

### ISSUE THREAD

**Issue by hugocoolens** [respeaker/seeed-voicecard#245]
After installing corbosman/pigpiod in a docker-container, the re-speaker sound is slowed down and shifted in frequency to the low frequencies. See also this discussion on thr Rhasspy-forum: 
[https://community.rhasspy.org/t/controlling-gpio-12-and-13-of-respeaker-2/1469/13?u=hugocoolens]

**Comment by hugocoolens** [comment]
The conflict can be avoided by adding an extra command line in the docker-compose.yml to choose PWM instead of PCM 
This is the pigpiod-part:
pigpiod:
  image: corbosman/pigpiod
  container_name: pigpiod
  restart: always
  privileged: true
  command: -t 0

**Comment by Pillar1989** [comment]
Is there anything we can do about it?

**Comment by hugocoolens** [comment]
It would be nice if the workaround I gave would not be necessary.

kind regards,
Hugo

Op di 17 nov. 2020 om 01:51 schreef Baozhu Zuo <notifications@github.com>:
