### ISSUE TITLE
ReSpeaker 4-Mics Linear Array Kit volume control with red cross in top panel (bar)

### ISSUE THREAD

**Issue by lxne** [respeaker/seeed-voicecard#247]
On my Raspberry Pi the volume control symbol in the top panel only shows a red cross if I select the seeed voicecard. Why can't I control the main volume off my 4-Mics Linear Array ReSpeaker with volume control as usual and expected?

![Bildschirmfoto 2020-09-08 um 21 24 03](https://user-images.githubusercontent.com/13134654/92519873-00391080-f21b-11ea-9d64-8ed5b124b88f.png)
![Bildschirmfoto 2020-09-08 um 21 24 18](https://user-images.githubusercontent.com/13134654/92519879-0202d400-f21b-11ea-943a-0270b49b3de5.png)

**Comment by Pillar1989** [comment]
https://github.com/respeaker/seeed-voicecard/issues/249

**Comment by turmary** [comment]
Solved in commit https://github.com/respeaker/seeed-voicecard/commit/e1110617b2dcb06c0191234b5b643187db2d58e4

**Comment by lxne** [comment]
Thanks. It works for me now.
