### ISSUE TITLE
PCM documentation needed

### ISSUE THREAD

**Issue by joshuajaharwood** [respeaker/seeed-voicecard#254]
The /etc/asound.conf file written during driver installation contains a number of PCMs with structures I've struggled to understand (and still to an extent do) due to lack of documentation. The defaults section is easy enough to understand, but the following issues stand out to me (while using a 6-mic circular, but most will affect other products too):

- What are the AC108 and AC101 ICs individually responsible for?
- Regarding PCMs in /etc/asound.conf...
  - What is the purpose of each PCM? How do they work?
  - Why is `pcm.multiapps` commented out?
  - Why set the default input and output to ALSA PCMs rather than Pulse, as is the Raspbian default?
  - Are these PCMs necessary to operate the card correctly?

Could we get some documentation elaborating on these, please? It is currently very unfriendly to beginners and hobbyists, who likely just want the source available in ALSA/Pulse ready for their desired application to use. It doesn't help that ALSA's documentation leaves much to be desired.

I'm happy to help write this documentation, but I'm not currently experienced enough with the Linux sound stack to reliably do so.

Please let me know what you think!

Thanks,
Josh

**Comment by Pillar1989** [comment]
We will be opening these up in the V2 release. In the current release, we have NDA with X-Powers AC108 and we can't go into any more details.  cc @HinTak
