### ISSUE TITLE
Respeaker 4-mics array with MAX98357 

### ISSUE THREAD

**Issue by IshantPundir** [respeaker/seeed-voicecard#260]
Hi, I am trying to run Respeaker 4-mics array with Adafruit MAX98357  i2s amp; I have tried installing Respeaker's driver and then MAX98357 driver, and vice versa, but after installing both drivers, only audio output from i2s is working, I am not seeing respeaker using arecord -L.

I would like to know how to make them both work together.

**Comment by Pillar1989** [comment]
Sorry, it's hard to use it together.
