### ISSUE TITLE
Please support Debian10 64 

### ISSUE THREAD

**Issue by HenryJi529** [respeaker/seeed-voicecard#262]
<img width="500" alt="Screenshot 2020-11-06 at 12 10 00" src="https://user-images.githubusercontent.com/41288155/98325112-ff5d0900-2028-11eb-912b-0d25241d9c11.png">

<img width="838" alt="Screenshot 2020-11-06 at 12 10 22" src="https://user-images.githubusercontent.com/41288155/98325137-0d128e80-2029-11eb-99c4-b327f5378f0d.png">

**Comment by Pillar1989** [comment]
This is not our problem, please go to the RPI forum feedback.
