### ISSUE TITLE
Unable to install on Arch system on raspi  

### ISSUE THREAD

**Issue by LeducH** [respeaker/seeed-voicecard#264]
I want to install the driver on an arch system on a raspberry
```
            OS: Arch Linux armv7l 
            Host: Raspberry Pi 3 Model B Rev 1.2 
```
when I run the install I get 

```
Error! echo
Your kernel headers for kernel -1-ARCH cannot be found at
/usr/lib/modules/-1-ARCH/build or /usr/lib/modules/-1-ARCH/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Can't compile with this kernel, aborting
Please try to compile with the option --compat-kernel
``` 

I tried ` sudo ./install.sh --compat-kernel` with the same result

**Comment by AIWintermuteAI** [comment]
Hello!
Arch Linux is outside of scope of official technical support for Raspberry Pi hat reSpeaker. Besides if you install Arch as your OS, you better know what you're doing ;)
https://github.com/respeaker/seeed-voicecard#technical-support
Feel free to create issue on the forum to see of there are any volunteers or ask question on Arch Linux forum  https://bbs.archlinux.org/

Closing the issue as it's outside of scope.
