### ISSUE TITLE
Scratchy noise on playback

### ISSUE THREAD

**Issue by potatoesrgood** [respeaker/seeed-voicecard#272]
Whenever I play the a recording back, my voice is almost completely drowned out by a sort of static. I am on a raspberry pi 4 and am running rasbian. I am also wearing earbuds.

**Comment by AIWintermuteAI** [comment]
Hi, @potatoesrgood !
I'll be closing the issue due to inactivity. If the issue persists, feel free to re-open - but do fill the template to give us a better idea about system set-up and exact circumstances you're encountering the problem in.

**Comment by HinTak** [comment]
Some recording samples would be good. Possibly a duplicate of https://github.com/respeaker/seeed-voicecard/issues/289 (faulty hardware)
