### ISSUE TITLE
What is purpose of master override?

### ISSUE THREAD

**Issue by shawaj** [respeaker/seeed-voicecard#280]
@HinTak do you know what the purpose of the override in the 2 mic overlay is?

`master = <0>,"=2!3";`

**Comment by HinTak** [comment]
No idea. Sorry.

**Comment by shawaj** [comment]
@HinTak no probs. Do you know anyone from Seeed that might?

**Comment by HinTak** [comment]
I am just amother user. Check the repo log

**Comment by shawaj** [comment]
@turmary any idea about this?

**Comment by Pillar1989** [comment]
Sorry, this is just a reference code from a copy somewhere, there is no deleted string. But anyway it doesn't affect any functionality, sorry for misleading people, it will be removed in the next release.
