### ISSUE TITLE
Pi Zero W not booting with the 2mic hat attached

### ISSUE THREAD

**Issue by SimonGurney** [respeaker/seeed-voicecard#29]
Hi,

As the title says, if i attach the board my Pi Zero W will not boot.  Could this be anything other than a hardware fault?

**Comment by Pillar1989** [comment]
No, Please check your hardware connection

**Comment by SimonGurney** [comment]
Working today, must have been a dry solder.  Sorry!

**Comment by SimonGurney** [comment]
I booted without the Hat, did a ./uninstalll 2mic, ./uninstall 4mic and then reinstalled.

All good now :D
