### ISSUE TITLE
(Grove GP12) I2S Microphone

### ISSUE THREAD

**Issue by SebAcou** [respeaker/seeed-voicecard#303]
Hello, 
I would like to add a PDM microphone (plugged on the the GP12 grove port). Is there build-in libraries or ressources on how to read the signal from this port?
Best Regards

**Comment by AIWintermuteAI** [comment]
Hello!
This seems to be a general question not a bug/feature request. It is better to be addressed in Seeed Forum reSpeaker subforum.
https://forum.seeedstudio.com/c/products/respeaker/15
