### ISSUE TITLE
[Bug]: ./install.sh on 64bit Raspberry OS

### ISSUE THREAD

**Issue by diphtong** [respeaker/seeed-voicecard#317]
### Describe the bug

following error when running ./install.sh:

E: Paket linux-raspi kann nicht gefunden werden.
E: Paket linux-headers-raspi kann nicht gefunden werden.
E: Paket linux-image-raspi kann nicht gefunden werden.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
libasound2-plugins ist schon die neueste Version (1.2.2-2).
dkms ist schon die neueste Version (2.8.4-3).
git ist schon die neueste Version (1:2.30.2-1).
i2c-tools ist schon die neueste Version (4.2-1+b1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
grep: /boot/kernel.img: No such file or directory

gzip: stdin: unexpected end of file
grep: /boot/kernel.img: No such file or directory

gzip: stdin: unexpected end of file
------------------------------------------------------
 WARNING Your loaded kernel version is 5.10.63
 Not matching the updated version .
 Kernel was updated, but new kernel was not loaded yet
 Please reboot your machine AND THEN run this script again

### Expected behavior

install the package

### Platform

- Device: Raspberry Pi CM4
- OS: Raspberry OS bullseye 64 bit
- Version/commit number [e.g. d1816f5]

**Comment by StuartIanNaylor** [comment]
```
 WARNING Your loaded kernel version is 5.10.92
 Not matching the updated version .
 Kernel was updated, but new kernel was not loaded yet
 Please reboot your machine AND THEN run this script again
```
```
pi@raspberrypi:~/seeed-voicecard $ uname -a
Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
```

**Comment by StuartIanNaylor** [comment]
sudo ./install_arm64.sh not  ./install.sh
