### ISSUE TITLE
How to trigger the LEDs of Respeaker2mic with AlexaPi ?

### ISSUE THREAD

**Issue by jabulonboaz** [respeaker/seeed-voicecard#32]
on a RaspberryPi zero w with an AlexaPi build.
How to trigger the top 3 LEDs of respeaker 2mic hat when Alexa listens and responds?

**Comment by Pillar1989** [comment]
For LEDs of Respeaker 2mic  you can refer to this https://github.com/respeaker/pixel_ring

**Comment by jabulonboaz** [comment]
@Pillar1989 thank u. This refers to the array jat but i have the 2mic hat. Anything relevant to 2mic hat please?

**Comment by Pillar1989** [comment]
2mic hat use 3 LEDs. Please change PIXELS_N to 3.
https://github.com/respeaker/pixel_ring/blob/master/pixel_ring/apa102_pixel_ring.py#L14

**Comment by jabulonboaz** [comment]
Can you make instructions to implement the respeaker 2mic leds with google assistant and AlexaPi projects please?

**Comment by Pillar1989** [comment]
Sorry, We are all in Chinese New Years. maybe you can ask for google assistant and AlexaPi projects projects developer to implement  LEDs.

**Comment by xiongyihui** [comment]
@jabulonboaz We have demos to use Google Assistant and Alexa Voice Service with LED light. See https://github.com/respeaker/mic_hat

**Comment by jabulonboaz** [comment]
Thank you i have implemented the LEDs with GA for now. I have read the git instructions in the past but they are not detailed enough. It would be good if you could update these with more detail.
