### ISSUE TITLE
Muffled audio via 3.5mm audio jack

### ISSUE THREAD

**Issue by nicklee1990** [respeaker/seeed-voicecard#35]
I have installed the linux kernel drivers for my Respeaker 2 mic pHat on my Pi Zero W and can confirm the microphone works perfectly (recorded audio out to file and played it back via a bluetooth speaker). However, when playing audio with the headphones connected to the headphone jack, the audio is barely audible and sounds garbled/muffled.

Does this sound like a hardware issue that may require a replacement Resepeaker 2 mic board?

Command used to test `arecord -f cd -Dhw:1 | aplay -Dhw:1`

**Comment by Pillar1989** [comment]
Maybe you can record a video for me, I can help you solve the issue.

**Comment by nicklee1990** [comment]
Tried on my Pi3 and it worked fine so looks like it could be a hardware issue specific to my Pi Zero. I need to take a look at the GPIO pins as I think there is an issue there. Will close this issue as it is unrelated to the Respeaker phat
