### ISSUE TITLE
Turn Off LED Permanently

### ISSUE THREAD

**Issue by nicklee1990** [respeaker/seeed-voicecard#37]
just wondering if there's a quick/easy way to turn off the white LED on the board that is switched on by default?

**Comment by xiongyihui** [comment]
I just updated the pixel_ring python library and added a command line tool `pixel_ring_check` which can be used to turn off the LEDs. Just run:

```
sudo pip install pixel_ring
pixel_ring_check
```

You can add it to a autorun script.

**Comment by nicklee1990** [comment]
worked perfectly
