### ISSUE TITLE
Can this driver work on other linux distributions like Ubuntu? What about some linux-based OSes like OpenWRT?

### ISSUE THREAD

**Issue by HSID** [respeaker/seeed-voicecard#38]
I want to use other OSes rather than raspbian for some reasons. Will that work?

**Comment by Pillar1989** [comment]
let's open a vote, If 50+ people need this feature, we'll develop it.

**Comment by HSID** [comment]
So the current version will only work for Raspbian?

**Comment by Pillar1989** [comment]
Yes

**Comment by Pillar1989** [comment]
Support ArchlinuxARM

**Comment by keelobight** [comment]
PLEASE let this work on ubuntu for pi.  Many of us hate using raspbian and paid for this card before realizing it's "raspian only"  come on guys, support your customers!!!!!

**Comment by Pillar1989** [comment]
@keelobight which ubuntu distribution do you like?

**Comment by keelobight** [comment]
Currently i use xubuntu and the most.  
I also have a libre computer ROC-RK3328-CC that runs ubuntu.  If you could make it work on that, i would buy another unit probably the more more expensive one .

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 3, 2018 at 7:17 AM, Baozhu Zuo<notifications@github.com> wrote:   
@keelobight which ubuntu distribution do you like?

**Comment by keelobight** [comment]
Are you really going to make it ubuntu compatible or are you just joking?

**Comment by Pillar1989** [comment]
@keelobight  I think current project support raspberry pi ubuntu system. Do you test it? what's the issue?

**Comment by keelobight** [comment]
sudo ./install.sh 2mic[sudo] password for alexapi: Hit:1 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu xenial InReleaseHit:2 http://ports.ubuntu.com xenial InReleaseHit:3 http://ports.ubuntu.com xenial-updates InReleaseHit:4 http://ports.ubuntu.com xenial-security InReleaseHit:5 http://ports.ubuntu.com xenial-backports InReleaseReading package lists... Done                     Building dependency tree       Reading state information... Done35 packages can be upgraded. Run 'apt list --upgradable' to see them.Reading package lists... DoneBuilding dependency tree       Reading state information... Doneraspberrypi-kernel-headers is already the newest version (1.20161215-1~xenial1.0).raspberrypi-kernel is already the newest version (1.20161215-1~xenial1.0).0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.Reading package lists... DoneBuilding dependency tree       Reading state information... Donedkms is already the newest version (2.2.0.3-2ubuntu11.5).git is already the newest version (1:2.7.4-0ubuntu1.3).i2c-tools is already the newest version (3.1.2-3~xenial1.0).0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
------------------------------Deleting module version: 0.3completely from the DKMS tree.------------------------------Done.
Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->                 /usr/src/seeed-voicecard-0.3
DKMS: add completed.Error! Your kernel headers for kernel 4.14.32+ cannot be found.Please install the linux-headers-4.14.32+ package,or use the --kernelsourcedir option to tell DKMS where it's locatedError! Your kernel headers for kernel 4.14.32-v7+ cannot be found.Please install the linux-headers-4.14.32-v7+ package,or use the --kernelsourcedir option to tell DKMS where it's located
Kernel preparation unnecessary for this kernel.  Skipping...
Building module:cleaning build area....make KERNELRELEASE=4.4.38+ -C /lib/modules/4.4.38+/build M=/var/lib/dkms/seeed-voicecard/0.3/build.......(bad exit status: 2)ERROR (dkms apport): binary package for seeed-voicecard: 0.3 not foundError! Bad return status for module build on kernel: 4.4.38+ (armv7l)Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.
Kernel preparation unnecessary for this kernel.  Skipping...
Building module:cleaning build area....make KERNELRELEASE=4.4.38-v7+ -C /lib/modules/4.4.38-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build.......(bad exit status: 2)ERROR (dkms apport): binary package for seeed-voicecard: 0.3 not foundError! Bad return status for module build on kernel: 4.4.38-v7+ (armv7l)Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.------------------------------------------------------Please reboot your raspberry pi to apply all settingsEnjoy!------------------------------------------------------
This is what I get not matter what distro I use.  Sorry I'm kind of a noob, but I've spent SO many hours trying to get this thing to work.  Can you please give me specific instructions on what to do?  I can get it to work on an old version of raspbian from 9-2017, so I know the hardware works, but I hate raspbian and only use other distros.  Please give me a little help here.  I've tried every ubuntu distro there is and even newer versions of raspian with no luck.  I'm starting to wish I hadn't spent money on this product that has such poor documentation.
    On Sunday, April 8, 2018, 1:07:21 AM GMT-5, Baozhu Zuo <notifications@github.com> wrote:  
 
 
@keelobight I think current project support raspberry pi ubuntu system. Do you test it? what's the issue?

**Comment by Pillar1989** [comment]
```
DKMS: add completed.Error! Your kernel headers for kernel 4.14.32+ cannot be found.Please install the linux-headers-4.14.32+ package,or use the --kernelsourcedir option to tell DKMS where it's locatedError! Your kernel headers for kernel 4.14.32-v7+ cannot be found.Please install the linux-headers-4.14.32-v7+ package,or use the --kernelsourcedir option to tell DKMS where it's located
```

raspberrypi.org only provide  4.14.30-v7+  headers. seeed-voicecard total support raspberry pi 4.14+ linux kernel.  But raspberry pi ubuntu lack of software package.

**Comment by keelobight** [comment]
Ok so i just need an older kernel?  No problem.  Which one works best?  Ive tried older ones and get the same result....

Sent from Yahoo Mail on Android 
 
  On Sun, Apr 8, 2018 at 3:35 AM, Baozhu Zuo<notifications@github.com> wrote:   DKMS: add completed.Error! Your kernel headers for kernel 4.14.32+ cannot be found.Please install the linux-headers-4.14.32+ package,or use the --kernelsourcedir option to tell DKMS where it's locatedError! Your kernel headers for kernel 4.14.32-v7+ cannot be found.Please install the linux-headers-4.14.32-v7+ package,or use the --kernelsourcedir option to tell DKMS where it's located

raspberrypi.org only provide 4.14.30-v7+ headers. seeed-voicecard total support raspberry pi 4.14+ linux kernel. But raspberry pi ubuntu lack of software package.

**Comment by Pillar1989** [comment]
@keelobight  4.14.30-v7+ headers and 4.14.30-v7+  kernel image ？

**Comment by Pillar1989** [comment]
Please reopen this issue if  it really generates demand.

**Comment by bogeuh** [comment]
i'd love to be able to use this on ubuntu (lubuntu). had to install it for my ros robot on a raspberry

sofar i got the leds to work

**Comment by bogeuh** [comment]
got it to work

**Comment by whb883** [comment]
I also need to use it in XXX Ubuntu Mate 16.04，Still no support plan?
