### ISSUE TITLE
Independent hp out and spk out?

### ISSUE THREAD

**Issue by tfontoura** [respeaker/seeed-voicecard#42]
2-mic HAT. 
As there are 2 independent controls in alsamixer, one for headphones and one for speaker, how do I find the hp device in order to update alsa asoundrc file to play  audio only to headphones?

**Comment by Pillar1989** [comment]
ln fact, headphones and speaker use the same hardware line.

**Comment by tfontoura** [comment]
I thought do, but there's an isolation somewhere, as there are independent volume controls in amixer and alsamixer.
