### ISSUE TITLE
Can't find seeed-4mic drivers on RPI3 Raspbian Stretch

### ISSUE THREAD

**Issue by melzoghbi** [respeaker/seeed-voicecard#47]
Hi,

I am running Raspbian Stretch on RPI3. After i installed the drivers and rebooted. i can't see the 4mic array drivers. Below is what i see when i list my audio drivers:

![image](https://user-images.githubusercontent.com/11993393/37986425-6a5b3d90-31c9-11e8-9d49-fde4b1d0a8de.png)

I have installed google assistant sdk previously and that's why you see voice drivers. I don't know what would be the ideal way to reset these drivers with respeaker ones.

here is the status of the seed voice card on my pi when i execute: systemctl status seeed-voicecard.service

![image](https://user-images.githubusercontent.com/11993393/37987235-9e688334-31cb-11e8-8eb3-16b2b4e8c678.png)

Thoughts on how to resolve this issue?

Thanks.

**Comment by turmary** [comment]
please paste result of command 'cat /var/log/seeed-voicecard.log' here.

**Comment by melzoghbi** [comment]
here you go:

+ dtparam i2c_arm=on
+ modprobe i2c-dev
+ dtparam spi=on
+ sleep 1
++ i2cdetect -y 1 0x1a 0x1a
++ grep 1a
++ awk '{print $2}'
+ is_1a=
++ i2cdetect -y 1 0x35 0x35
++ grep 35
++ awk '{print $2}'
+ is_35=
++ i2cdetect -y 1 0x3b 0x3b
++ grep 3b
++ awk '{print $2}'
+ is_3b=3b
+ '[' x == x1a ']'
+ '[' x3b == x3b ']'
+ '[' x == x ']'
+ echo 'install 4mic'
install 4mic
+ dtoverlay seeed-4mic-voicecard
* Failed to apply overlay '5_seeed-4mic-voicecard' (kernel)
+ sleep 1
++ arecord -l
++ grep seeed4micvoicec
++ awk '{print $2}'
++ sed s/://
+ hw=
+ cp /etc/voicecard/asound_4mic.conf /etc/asound.conf
+ echo 'get slavepcm line number'
get slavepcm line number
++ grep -n ac108-slavepcm /etc/asound.conf
++ awk '{print $1}'
++ sed s/://
+ line=28
+ echo 'delete 28 slavepcm hw number'
delete 28 slavepcm hw number
+ sed -i -e 28d /etc/asound.conf
+ echo 'insert slavepcm hw:,0'
insert slavepcm hw:,0
+ sed -i '28i slave.pcm "hw:,0"' /etc/asound.conf
+ cp /etc/voicecard/ac108_asound.state /var/lib/alsa/asound.state
+ '[' x3b == x3b ']'
+ '[' x == x35 ']'
+ alsactl restore
+ amixer cset numid=3 1
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=1

**Comment by turmary** [comment]
you need to remove 'dtoverlay=googlevoicehat-soundcard' in /boot/config.txt, due to they are conflict, maybe.

**Comment by melzoghbi** [comment]
Please ignore the previous output since i started from a fresh raspbian OS and here is the current output:

![image](https://user-images.githubusercontent.com/11993393/38096023-daaaaeba-333f-11e8-92b3-5ee63d37d0e8.png)

**Comment by turmary** [comment]
Hi melzoghbi,
please try install the new [version](https://github.com/respeaker/seeed-voicecard/tree/031bbb3a1a19c5c0bcdf2b371439bd1aeca41158).

**Comment by turmary** [comment]
Please don't run rpi-update or else driver will fail due to kernel-headers for 4.14.31 unavailable.

**Comment by chhsiao90** [comment]
Same problem and same log here.
Is there anything I can do? Thanks!

```
Raspberry Pi: RASPBERRY PI 2 MODEL B
seeed-voicecard: 86329f0719c61405a17a0e5c6c04806d234ba086
Kernel: Linux raspberrypi 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux
```

**Comment by chhsiao90** [comment]
My problem solved, it looks like that I had config conflict in /boot/config.txt

**Comment by melzoghbi** [comment]
Hi @turmary 

I installed the latest version but still i am having the same issue. 

Here is the output of -uname as per your request:

![image](https://user-images.githubusercontent.com/11993393/38148876-4377e2c8-3426-11e8-8fc3-7ea4dc79c27b.png)

**Comment by Pillar1989** [comment]
@melzoghbi  Please close all of your issues.

**Comment by melzoghbi** [comment]
ok.
