### ISSUE TITLE
Pi won't even recognize 4mic respeaker

### ISSUE THREAD

**Issue by ocaduacelab** [respeaker/seeed-voicecard#58]
Hi. I'm running Jessie and I've followed these install instructions for a 4mic raspberry pi hat. And my Pi can't even recognize the respeaker. How do I fix this? My output after running arecord -L is:

```
null
Discard all samples (playback) or generate zero samples (capture)
pulse
PulseAudio Sound Server
```

That's it. What do I do to get this thing working?

Thanks.

**Comment by turmary** [comment]
For Raspbian Jessie, please refer @ #40.
