### ISSUE TITLE
files missing for 4-mic hat

### ISSUE THREAD

**Issue by shivasiddharth** [respeaker/seeed-voicecard#6]
installation instructions for the 4-mic hat given in the wiki do not match the files in the git.

**Comment by Pillar1989** [comment]
If you received the board from seeedstudio.com. You will see the driver code in the git.

**Comment by shivasiddharth** [comment]
@Pillar1989 , the "install_4mic.sh" is not there in this git. And AC108 folder is also not there.

**Comment by shivasiddharth** [comment]
ok, you have added them now.. cool
