### ISSUE TITLE
Help to find out the right powerful speaker for Respeaker 2MIC HAT board

### ISSUE THREAD

**Issue by titusece** [respeaker/seeed-voicecard#61]
Hello,
I have respeaker 2mic HAT board and I would like to connect the powerful speakers via JST connector.
Can you please tell me what is the maximum supported Watts and Ohms for connecting speaker.
Thanks for the help.

**Comment by Pillar1989** [comment]
![image](https://user-images.githubusercontent.com/4081906/38463809-4b49e0bc-3b35-11e8-85e5-888076ad26ef.png)
copy from wm8960 datasheet: https://github.com/SeeedDocument/Bazzar_Attachment/raw/master/107100001/WM8960%20Datasheet.pdf

**Comment by titusece** [comment]
Thanks for the help.
