### ISSUE TITLE
Powering Respeaker 2-Mic with Pi3B

### ISSUE THREAD

**Issue by firzanarmani** [respeaker/seeed-voicecard#64]
Hi,

I understand that another MicroUSB should be connected to the repealed for adequate power for the respeaker. Otherwise, the Pi3B will warn of undervoltage.

Is this a limitation of the Pi3B power to the respeaker? Can this be solved using only one power supply/wire?

Sorry I'm pretty new to this stuff. I'm enjoying the Respeaker 2 Mic pi hat!

**Comment by gerardwr** [comment]
Recently bought an RPI3+ and a Respeaker 2-mic, here's my experience.

Without the Respeaker attached, the RPi RED power led goes out for a short while on a regular basis. Changing power supply and USB cable did not fix this.

With the RPI1 I have this had never been an issue. But the RPi3 gets much warmer, uses more power.

When I attached the Respeaker the RED Rpi3 led went out even more often. When I added a USB power cable to the Respeaker the RED RPI3 Led is rocksolid RED. But USB power cables were attached to the same multiple USB-output power brick.

So, using a single power supply for both RPi3 and Respeaker is OK, provided it can deliver enough power.

Make sure to use a USB cable that capable of providing enought current, several USB cables I tried could not provide enough current to the RPI3+
