### ISSUE TITLE
Error when Installing Respeaker 2-mic HAT drivers on Orange Pi

### ISSUE THREAD

**Issue by gerardwr** [respeaker/seeed-voicecard#69]
I tried setting up the Respeaker software acc. this Github on an Orange Pi, but get the following error:
```
pi@orangepione:~/seeed-voicecard$ sudo ./install.sh 
cat: /proc/device-tree/model: No such file or directory
Sorry, this drivers only works on raspberry pi
```

In general installing software for the Raspberry Pi will install fine on an Orange Pi.

Can I change the install.sh for the Orange PI?

**Comment by Pillar1989** [comment]
Sorry, this drivers only works on raspberry pi

**Comment by gerardwr** [comment]
@Pillar1989 
That's a shame. 

The CPU is on the Orange PI is an Arm, like on the RPi. Is there an obvious reason why the Respeaker would not run on the Orange?

**Comment by Pillar1989** [comment]
Thay are different. You can compare bcm2835 and allwinner h3/h5/h6 datasheet.

**Comment by gerardwr** [comment]
@Pillar1989 

OK, thanks for your confirmation.
