### ISSUE TITLE
2 Mic Hat Schematic  

### ISSUE THREAD

**Issue by salmanfarisvp** [respeaker/seeed-voicecard#70]
Can you please provide **2 Mic Hat Schematic**  , can't find it anywhere . Thanks.

**Comment by Pillar1989** [comment]
https://github.com/SeeedDocument/MIC_HATv1.0_for_raspberrypi/raw/master/src/ReSpeaker%202-Mics%20Pi%20HAT_SCH.pdf

**Comment by salmanfarisvp** [comment]
Thank you @Pillar1989  .
