### ISSUE TITLE
seeed-voicecard 4-mic cannot arecord -d 10 test.wav

### ISSUE THREAD

**Issue by meischdaddy30** [respeaker/seeed-voicecard#84]
Hi all,

I'm building an MMM-Assistant for my magic mirror and when I'm trying to do $arecord -d 10 test.wav I'm getting "ALSA lib pcm_direct.c:1765:(snd1_pcm_direct_parse_open_conf) Unknown field ac108-slavepcm arecord: main:788: audio open error: Invalid argument"

I've updated my /etc/asound.conf based on this https://github.com/respeaker/seeed-voicecard/blob/master/asound_4mic.conf but it's still not working.

What's weird though is that if I open audacity then I can record and playback just fine.  Everything is updated and working well besides this.  I've tried reinstalling seeed-voicecard but that didn't work..If anyone has any ideas on what I can try it would be greatly appreciated.

**Comment by JonahKr** [comment]
@meischdaddy30  maybe you can share how you resolved the problem ... since i have the same atm
