### ISSUE TITLE
Respeaker 4 Mic Linear Array Kit Algorithm support and Far Field tested distance

### ISSUE THREAD

**Issue by ash-lat** [respeaker/seeed-voicecard#88]
Hi 

I just saw the Respeaker 4 Mic linear Array is up for sale.

1. Does this support noise suppression, echo cancellation, AGC, De-reverberation algorithms in it? 
2. What would be the far field support tested on this one ( in metres) ?
3. Or would the new 6 Mic Circular array have better performance over this one for speech recognition application like (AVS, Baidu, snowboy)

Thanks in advance

**Comment by Pillar1989** [comment]
@ash-lat 

    Does this support noise suppression, echo cancellation, AGC, De-reverberation algorithms in it?
>>  Respeaker 4 Mic linear Array or  6 Mic Circular array , they are only the wonderful hardware to support algorithms which you mentioned. You can find the algorithm you want in the relevant algorithm software company.
    What would be the far field support tested on this one ( in metres) ?
>> Microphone sensitivity, we tested  within a range of 5 meters 
    Or would the new 6 Mic Circular array have better performance over this one for speech recognition application like (AVS, Baidu, snowboy)
>> In theory, what you said is right.

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
