### ISSUE TITLE
Can this driver work on Ubuntu mate 16.04 ?

### ISSUE THREAD

**Issue by zhtsky** [respeaker/seeed-voicecard#9]
I have installed this driver on raspberry pi (Ubuntu mate 16.04LTS), but I can't use it.

**Comment by Pillar1989** [comment]
Can you show me your /boot/config.txt

**Comment by zhtsky** [comment]
@Pillar1989 
[config.txt](https://github.com/respeaker/seeed-voicecard/files/1326973/config.txt)

**Comment by Pillar1989** [comment]
It seems everything is fine!

**Comment by zhtsky** [comment]
@Pillar1989  
I think so, too！ But  when I use cmd "aplay -l", I can't see seeed-2mic-voicecard.

**Comment by Pillar1989** [comment]
do you insert the hat to your pi ? then reboot the board

**Comment by zhtsky** [comment]
@Pillar1989 
Yes, I have installed this driver on raspbian-jessie in the same way, it works fine.
But on the ubuntu mate, it doesn't work.

**Comment by Pillar1989** [comment]
#

**Comment by Pillar1989** [comment]
I'll test it on mate tomorrow

**Comment by Pillar1989** [comment]
I'm so sorry , Ubuntu  mate  used the old rasperry pi linux kernel(4.4) . We only support linux 4.9 kernel.

**Comment by zhtsky** [comment]
@Pillar1989 
Ok, I know, thank you very much!
