### ISSUE TITLE
I2C Address ? 

### ISSUE THREAD

**Issue by singledo** [respeaker/seeed-voicecard#90]
i want to know the address of AC108 ( four mic arry ) ? thanks for you help .

**Comment by Pillar1989** [comment]
mic arry use two ac108  chips, one i2c address is 0x35 and the other one is 0x3b, You can check it by follow url.
https://github.com/respeaker/seeed-voicecard/blob/master/seeed-8mic-voicecard-overlay.dts#L57
https://github.com/respeaker/seeed-voicecard/blob/master/seeed-8mic-voicecard-overlay.dts#L65

**Comment by singledo** [comment]
thanks for your help  very much .

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
